- charts/magento/v1.0.1/app-readme.md
- charts/magento/v1.0.1/questions.yml
- charts/mariadb/v3.0.3/questions.yml
- charts/memcached/v2.0.4/app-readme.md
- charts/memcached/v2.0.4/questions.yml
- charts/mongodb-replicaset/v3.3.0/questions.yml
- charts/mongodb/v2.0.1/questions.yml
- charts/mysql/v0.3.7/questions.yml
- charts/redis/v3.0.2/questions.yml
- charts/wordpress/v1.0.2/app-readme.md
- charts/wordpress/v1.0.2/questions.yml
- proposed/longhorn/v0.1.0/app-readme.md
- proposed/longhorn/v0.1.0/questions.yml
Some updates to the text in the charts.
> Text updates

- proposed/longhorn/latest/README.md
- proposed/longhorn/latest/app-readme.md
https://github.com/rancher/longhorn/issues/261
RFR
> Update Longhorn chart documentation

- charts/wordpress/v1.0.5/questions.yml
> wordpress: Add existingClaim to the options

- charts/artifactory-ha/v0.2.2/templates/nginx-pvc.yaml
https://github.com/rancher/rancher/issues/15681
> Fix JFrog issue

- charts/fluentd-aggregator/latest/.helmignore
- charts/fluentd-aggregator/latest/Chart.yaml
- charts/fluentd-aggregator/latest/README.md
- charts/fluentd-aggregator/latest/app-readme.md
- charts/fluentd-aggregator/latest/questions.yml
- charts/fluentd-aggregator/latest/templates/NOTES.txt
- charts/fluentd-aggregator/latest/templates/_helpers.tpl
- charts/fluentd-aggregator/latest/templates/configmap.yaml
- charts/fluentd-aggregator/latest/templates/ingress.yaml
- charts/fluentd-aggregator/latest/templates/secert.yaml
- charts/fluentd-aggregator/latest/templates/service-headless.yaml
- charts/fluentd-aggregator/latest/templates/service.yaml
- charts/fluentd-aggregator/latest/templates/statefulset.yaml
- charts/fluentd-aggregator/latest/values.yaml
> add fluentd aggregator v0.1.0 chart #91

- proposed/longhorn/latest/Chart.yaml
- proposed/longhorn/latest/README.md
- proposed/longhorn/latest/templates/postupgrade-job.yaml
- proposed/longhorn/latest/values.yaml
- proposed/longhorn/v0.3.2/.helmignore
- proposed/longhorn/v0.3.2/Chart.yaml
- proposed/longhorn/v0.3.2/README.md
- proposed/longhorn/v0.3.2/app-readme.md
- proposed/longhorn/v0.3.2/questions.yml
- proposed/longhorn/v0.3.2/templates/NOTES.txt
- proposed/longhorn/v0.3.2/templates/_helpers.tpl
- proposed/longhorn/v0.3.2/templates/clusterrole.yaml
- proposed/longhorn/v0.3.2/templates/clusterrolebinding.yaml
- proposed/longhorn/v0.3.2/templates/crds.yaml
- proposed/longhorn/v0.3.2/templates/daemonset-sa.yaml
- proposed/longhorn/v0.3.2/templates/deployment-driver.yaml
- proposed/longhorn/v0.3.2/templates/deployment-ui.yaml
- proposed/longhorn/v0.3.2/templates/ingress.yaml
- proposed/longhorn/v0.3.2/templates/serviceaccount.yaml
- proposed/longhorn/v0.3.2/templates/storageclass.yaml
- proposed/longhorn/v0.3.2/templates/tls-secrets.yaml
- proposed/longhorn/v0.3.2/templates/uninstall-job.yaml
- proposed/longhorn/v0.3.2/values.yaml
https://github.com/rancher/longhorn/issues/337
https://github.com/rancher/longhorn/issues/322
> Longhorn v0.3.3

- proposed/openebs/latest/Chart.yaml
- proposed/openebs/latest/templates/deployment-maya-apiserver.yaml
* Update maya-apiserver labels
* Update chart version in Charts.yaml
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
> [openebs] update maya-apiserver labels

- charts/fluentd-aggregator/latest/Chart.yaml
- charts/fluentd-aggregator/latest/questions.yml
- charts/fluentd-aggregator/latest/templates/configmap.yaml
update fluentd to fix output plugins
> update fluentd to fix output plugins

- charts/fluentd-aggregator/v0.2.1/.helmignore
- charts/fluentd-aggregator/v0.2.1/Chart.yaml
- charts/fluentd-aggregator/v0.2.1/README.md
- charts/fluentd-aggregator/v0.2.1/app-readme.md
- charts/fluentd-aggregator/v0.2.1/questions.yml
- charts/fluentd-aggregator/v0.2.1/templates/NOTES.txt
- charts/fluentd-aggregator/v0.2.1/templates/_helpers.tpl
- charts/fluentd-aggregator/v0.2.1/templates/configmap.yaml
- charts/fluentd-aggregator/v0.2.1/templates/ingress.yaml
- charts/fluentd-aggregator/v0.2.1/templates/secert.yaml
- charts/fluentd-aggregator/v0.2.1/templates/service-headless.yaml
- charts/fluentd-aggregator/v0.2.1/templates/service.yaml
- charts/fluentd-aggregator/v0.2.1/templates/statefulset.yaml
- charts/fluentd-aggregator/v0.2.1/values.yaml
Aim of this change is to allow additional persistent volume which will be used to other purposes than just buffer which we have currently. As an example we can store part of the log messages on this volume when backed will not be available.
> Enable extra persistence using PVC

- proposed/nfs-provisioner/latest/Chart.yaml
- proposed/nfs-provisioner/latest/questions.yml
- proposed/nfs-provisioner/latest/templates/statefulset.yaml
- proposed/nfs-provisioner/latest/values.yaml
Update nfs-provisioner to use hostpath if persistence is not set
Related Issues:
#135
> Update nfs-provisioner to use hostpath if persistence is not set

- proposed/openebs/latest/Chart.yaml
- proposed/openebs/latest/README.md
- proposed/openebs/latest/questions.yml
- proposed/openebs/latest/templates/cm-node-disk-manager.yaml
- proposed/openebs/latest/templates/daemonset-ndm.yaml
- proposed/openebs/latest/templates/deployment-maya-apiserver.yaml
- proposed/openebs/latest/templates/deployment-maya-provisioner.yaml
- proposed/openebs/latest/templates/deployment-maya-snapshot-operator.yaml
- proposed/openebs/latest/values.yaml
- Updated chart version
- Added liveness probe in all control-plane component templates
- Change NDM update strategy to 'RollingUpdate'
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
> [openebs] update charts to latest 0.8.1 release (#11650)

- charts/openebs/latest/Chart.yaml
- charts/openebs/latest/README.md
- charts/openebs/latest/questions.yml
- charts/openebs/latest/templates/daemonset-ndm.yaml
- charts/openebs/latest/values.yaml
Signed-off-by: prateekpandey14 <prateek.pandey@openebs.io>
> [openebs] update NDM to 0.3.5 release

- charts/wordpress/latest/Chart.yaml
- charts/wordpress/latest/app-readme.md
- charts/wordpress/latest/questions.yml
- charts/wordpress/latest/requirements.lock
- charts/wordpress/latest/templates/pvc.yaml
Problem:
https://github.com/rancher/charts/issues/161
Solution: add existing volume claim of the WordPress
> add existing volume claim of the wordpress

- charts/wordpress/latest/Chart.yaml
fix CI lint failure of invalid wp maintainer @ https://drone-pr.rancher.io/rancher/charts/114/1/2
> fix CI lint failure of invalid wp maintainer

- .drone.yml
https://github.com/rancher/charts/pull/207
> Update drone lint chart image

- proposed/longhorn/latest/Chart.yaml
- proposed/longhorn/latest/questions.yml
- proposed/longhorn/latest/templates/clusterrole.yaml
- proposed/longhorn/latest/templates/clusterrolebinding.yaml
- proposed/longhorn/latest/templates/crds.yaml
- proposed/longhorn/latest/templates/daemonset-sa.yaml
- proposed/longhorn/latest/templates/default-setting.yaml
- proposed/longhorn/latest/templates/deployment-driver.yaml
- proposed/longhorn/latest/templates/deployment-ui.yaml
- proposed/longhorn/latest/values.yaml
- proposed/longhorn/v0.5.0/.helmignore
- proposed/longhorn/v0.5.0/Chart.yaml
- proposed/longhorn/v0.5.0/README.md
- proposed/longhorn/v0.5.0/app-readme.md
- proposed/longhorn/v0.5.0/questions.yml
- proposed/longhorn/v0.5.0/templates/NOTES.txt
- proposed/longhorn/v0.5.0/templates/_helpers.tpl
- proposed/longhorn/v0.5.0/templates/clusterrole.yaml
- proposed/longhorn/v0.5.0/templates/clusterrolebinding.yaml
- proposed/longhorn/v0.5.0/templates/crds.yaml
- proposed/longhorn/v0.5.0/templates/daemonset-sa.yaml
- proposed/longhorn/v0.5.0/templates/deployment-driver.yaml
- proposed/longhorn/v0.5.0/templates/deployment-ui.yaml
- proposed/longhorn/v0.5.0/templates/ingress.yaml
- proposed/longhorn/v0.5.0/templates/postupgrade-job.yaml
- proposed/longhorn/v0.5.0/templates/serviceaccount.yaml
- proposed/longhorn/v0.5.0/templates/storageclass.yaml
- proposed/longhorn/v0.5.0/templates/tls-secrets.yaml
- proposed/longhorn/v0.5.0/templates/uninstall-job.yaml
- proposed/longhorn/v0.5.0/values.yaml
> Longhorn: Longhorn v0.6.0 release

- charts/cert-manager/v0.3.2/questions.yml
- charts/cert-manager/v0.4.1/questions.yml
- charts/cert-manager/v0.5.2/questions.yml
Add min and max version filter to cert-manger
> Add min and max version filter to cert-manger

- charts/cert-manager/v0.9.1/app-readme.md
Add cert manager upgrade notes
> Add cert manager upgrade notes

- charts/prometheus/v9.1.0/templates/alertmanager/alertmanager-deployment.yaml
Update prometheus alertmanager api version to apps/v1
**Related Issue:**
https://github.com/rancher/rancher/issues/23458
> Update prometheus alertmanager api version

- charts/prometheus/v9.1.0/templates/alertmanager/alertmanager-deployment.yaml
> Revert "Update prometheus alertmanager api version"

- .drone.yml
> Update CI chart-testing image

- charts/instana-agent/v1.0.18/Chart.yaml
- charts/instana-agent/v1.0.18/OWNERS
- charts/instana-agent/v1.0.18/README.md
- charts/instana-agent/v1.0.18/app-readme.md
- charts/instana-agent/v1.0.18/questions.yml
- charts/instana-agent/v1.0.18/templates/NOTES.txt
- charts/instana-agent/v1.0.18/templates/_helpers.tpl
- charts/instana-agent/v1.0.18/templates/agentsecret.yaml
- charts/instana-agent/v1.0.18/templates/clusterrole.yaml
- charts/instana-agent/v1.0.18/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.18/templates/configmap.yaml
- charts/instana-agent/v1.0.18/templates/daemonset.yaml
- charts/instana-agent/v1.0.18/templates/downloadsecret.yaml
- charts/instana-agent/v1.0.18/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.18/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.18/values.yaml
This changeset includes:
- Another `instana/agent` Docker image version update from 1.0.28 to 1.0.29
- Some changes in the README
> [instana-agent/v1.0.18] Update instana/agent Docker image to latest 1.0.29. Update introduction in README

- proposed/longhorn/v0.1.0/questions.yml
- proposed/longhorn/v0.3.0/questions.yml
- proposed/longhorn/v0.3.1/questions.yml
- proposed/longhorn/v0.3.2/questions.yml
- proposed/longhorn/v0.3.3/questions.yml
- proposed/longhorn/v0.4.0/questions.yml
- proposed/longhorn/v0.4.1/questions.yml
- proposed/longhorn/v0.5.0/README.md
https://github.com/rancher/rancher/issues/23661
> Add max_rancher_version labels to Longhorn charts

- charts/openebs/v1.3.0/questions.yml
- This change will fix https://github.com/rancher/rancher/issues/23534
Signed-off-by: ChandanSagar <chandan.pradhan@mayadata.io>
> Updated questions.yml to fix rancher/rancher#23534

- charts/grafana/v3.8.6/Chart.yaml
- charts/magento/v5.1.4/Chart.yaml
- charts/prometheus/v9.1.0/Chart.yaml
- charts/prometheus/v9.1.0/charts/grafana/Chart.yaml
- charts/prometheus/v9.1.0/requirements.yaml
Problem:
logs show the following:
```
2019/11/04 12:08:21 [INFO] Updating global catalog library 2019/11/04 12:08:22 [INFO] Helm icon error: unknown file type [files://../grafana-logo.png] 2019/11/04 12:08:22 [INFO] Helm icon error: open management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078/charts/kafka/v0.8.0/logo.png: no such file or directory 2019/11/04 12:08:22 [INFO] Helm icon error: unknown file type [files://../logo.png] 2019/11/04 12:08:22 [INFO] Helm icon error: unknown file type [files://../logo.png] 2019/11/04 12:08:22 [INFO] Catalog sync done. 38 templates created, 0 templates updated, 0 templates deleted 2019/11/04 12:08:22 [ERROR] CatalogController library [catalog] failed with : failed to sync templates. Resetting commit. Multiple …
```
> Fix typo error files to file

- charts/traefik/v1.7/questions.yml
> updated questions.yaml to match values.yaml

- README.md
**Problem:**
update readme doc of missing variable types in `questions.yml`
**Related Issue:**
https://github.com/rancher/charts/issues/334
> Update readme of supported questions types

- charts/kubemq/v0.1.0/questions.yml
Fix kubeMQ partner label indent
> Fix kubeMQ label indent

- charts/cockroachdb/19.1.5/Chart.yaml
- charts/cockroachdb/19.1.5/OWNERS
- charts/cockroachdb/19.1.5/README.md
- charts/cockroachdb/19.1.5/app-readme.md
- charts/cockroachdb/19.1.5/questions.yml
- charts/cockroachdb/19.1.5/templates/NOTES.txt
- charts/cockroachdb/19.1.5/templates/_helpers.tpl
- charts/cockroachdb/19.1.5/templates/cluster-init.yaml
- charts/cockroachdb/19.1.5/templates/clusterrole.yaml
- charts/cockroachdb/19.1.5/templates/clusterrolebinding.yaml
- charts/cockroachdb/19.1.5/templates/networkpolicy.yaml
- charts/cockroachdb/19.1.5/templates/pdb.yaml
- charts/cockroachdb/19.1.5/templates/role.yaml
- charts/cockroachdb/19.1.5/templates/rolebinding.yaml
- charts/cockroachdb/19.1.5/templates/service-discovery.yaml
- charts/cockroachdb/19.1.5/templates/service.yaml
- charts/cockroachdb/19.1.5/templates/serviceaccount.yaml
- charts/cockroachdb/19.1.5/templates/statefulset.yaml
- charts/cockroachdb/19.1.5/templates/tests/client-test.yaml
- charts/cockroachdb/19.1.5/values.yaml
Replicates latest Helm chart and adds app-readme.md and questions.yml with initial support for Rancher advanced config
> Add CockroachDB

- charts/openebs/v1.5.0/Chart.yaml
- charts/openebs/v1.5.0/README.md
- charts/openebs/v1.5.0/app-readme.md
- charts/openebs/v1.5.0/questions.yml
- charts/openebs/v1.5.0/templates/NOTES.txt
- charts/openebs/v1.5.0/templates/_helpers.tpl
- charts/openebs/v1.5.0/templates/clusterrole.yaml
- charts/openebs/v1.5.0/templates/clusterrolebinding.yaml
- charts/openebs/v1.5.0/templates/cm-node-disk-manager.yaml
- charts/openebs/v1.5.0/templates/daemonset-ndm.yaml
- charts/openebs/v1.5.0/templates/deployment-admission-server.yaml
- charts/openebs/v1.5.0/templates/deployment-local-provisioner.yaml
- charts/openebs/v1.5.0/templates/deployment-maya-apiserver.yaml
- charts/openebs/v1.5.0/templates/deployment-maya-provisioner.yaml
- charts/openebs/v1.5.0/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/v1.5.0/templates/deployment-ndm-operator.yaml
- charts/openebs/v1.5.0/templates/service-maya-apiserver.yaml
- charts/openebs/v1.5.0/templates/serviceaccount.yaml
- charts/openebs/v1.5.0/values.yaml
- Updated chart version
- Updated questions.yml
- Updated deployment-local-provisioner.yaml
- Updated deployment-maya-apiserver.yaml
- Updated deployment-ndm-operator.yaml
Signed-off-by: ChandanSagar <chandan.pradhan@mayadata.io>
> Update charts to 1.5.0 release of OpenEBS

- charts/portworx/v1.0.4/Chart.yaml
- charts/portworx/v1.0.4/README.md
- charts/portworx/v1.0.4/app-readme.md
- charts/portworx/v1.0.4/ci/test-values.yaml
- charts/portworx/v1.0.4/questions.yml
- charts/portworx/v1.0.4/templates/NOTES.txt
- charts/portworx/v1.0.4/templates/_helpers.tpl
- charts/portworx/v1.0.4/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx/v1.0.4/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
- charts/portworx/v1.0.4/templates/portworx-controller.yaml
- charts/portworx/v1.0.4/templates/portworx-csi.yaml
- charts/portworx/v1.0.4/templates/portworx-ds.yaml
- charts/portworx/v1.0.4/templates/portworx-lighthouse.yaml
- charts/portworx/v1.0.4/templates/portworx-rbac-config.yaml
- charts/portworx/v1.0.4/templates/portworx-service.yaml
- charts/portworx/v1.0.4/templates/portworx-storageclasses.yaml
- charts/portworx/v1.0.4/templates/portworx-stork.yaml
- charts/portworx/v1.0.4/templates/serviceaccount-hook.yaml
- charts/portworx/v1.0.4/values.yaml
* added support for rancher v2.3+ 
* fixed unsupported 'none' in arguments
* updated px-account permissions
> portworx release 104

- charts/instana-agent/v1.0.20/.helmignore
- charts/instana-agent/v1.0.20/Chart.yaml
- charts/instana-agent/v1.0.20/OWNERS
- charts/instana-agent/v1.0.20/README.md
- charts/instana-agent/v1.0.20/app-readme.md
- charts/instana-agent/v1.0.20/questions.yml
- charts/instana-agent/v1.0.20/templates/NOTES.txt
- charts/instana-agent/v1.0.20/templates/_helpers.tpl
- charts/instana-agent/v1.0.20/templates/agentsecret.yaml
- charts/instana-agent/v1.0.20/templates/clusterrole.yaml
- charts/instana-agent/v1.0.20/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.20/templates/configmap.yaml
- charts/instana-agent/v1.0.20/templates/daemonset.yaml
- charts/instana-agent/v1.0.20/templates/downloadsecret.yaml
- charts/instana-agent/v1.0.20/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.20/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.20/values.yaml
This changeset includes:
- Add `POD_IP` env variable to the `instana-agent` container spec to make binding more stable
> Chart version 1.0.20

- charts/portworx/v1.0.5/Chart.yaml
- charts/portworx/v1.0.5/README.md
- charts/portworx/v1.0.5/app-readme.md
- charts/portworx/v1.0.5/ci/test-values.yaml
- charts/portworx/v1.0.5/questions.yml
- charts/portworx/v1.0.5/templates/NOTES.txt
- charts/portworx/v1.0.5/templates/_helpers.tpl
- charts/portworx/v1.0.5/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx/v1.0.5/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
- charts/portworx/v1.0.5/templates/portworx-controller.yaml
- charts/portworx/v1.0.5/templates/portworx-csi.yaml
- charts/portworx/v1.0.5/templates/portworx-ds.yaml
- charts/portworx/v1.0.5/templates/portworx-lighthouse.yaml
- charts/portworx/v1.0.5/templates/portworx-rbac-config.yaml
- charts/portworx/v1.0.5/templates/portworx-service.yaml
- charts/portworx/v1.0.5/templates/portworx-storageclasses.yaml
- charts/portworx/v1.0.5/templates/portworx-stork.yaml
- charts/portworx/v1.0.5/templates/serviceaccount-hook.yaml
- charts/portworx/v1.0.5/values.yaml
changed ports for portworx-service and portworx-api
> px release 1.0.5 

- charts/openebs/v1.6.0/Chart.yaml
- charts/openebs/v1.6.0/README.md
- charts/openebs/v1.6.0/app-readme.md
- charts/openebs/v1.6.0/questions.yml
- charts/openebs/v1.6.0/templates/NOTES.txt
- charts/openebs/v1.6.0/templates/_helpers.tpl
- charts/openebs/v1.6.0/templates/clusterrole.yaml
- charts/openebs/v1.6.0/templates/clusterrolebinding.yaml
- charts/openebs/v1.6.0/templates/cm-node-disk-manager.yaml
- charts/openebs/v1.6.0/templates/daemonset-ndm.yaml
- charts/openebs/v1.6.0/templates/deployment-admission-server.yaml
- charts/openebs/v1.6.0/templates/deployment-local-provisioner.yaml
- charts/openebs/v1.6.0/templates/deployment-maya-apiserver.yaml
- charts/openebs/v1.6.0/templates/deployment-maya-provisioner.yaml
- charts/openebs/v1.6.0/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/v1.6.0/templates/deployment-ndm-operator.yaml
- charts/openebs/v1.6.0/templates/psp-clusterrole.yaml
- charts/openebs/v1.6.0/templates/psp-clusterrolebinding.yaml
- charts/openebs/v1.6.0/templates/psp.yaml
- charts/openebs/v1.6.0/templates/service-maya-apiserver.yaml
- charts/openebs/v1.6.0/templates/serviceaccount.yaml
- charts/openebs/v1.6.0/values.yaml
- Updated chart version
- Updated clusterrole.yaml
- Added PodSecurityPolicies
Signed-off-by: ChandanSagar <chandan.pradhan@mayadata.io>
> Update charts to 1.6.0 release of OpenEBS

- charts/portworx/v1.0.6/Chart.yaml
- charts/portworx/v1.0.6/README.md
- charts/portworx/v1.0.6/app-readme.md
- charts/portworx/v1.0.6/ci/test-values.yaml
- charts/portworx/v1.0.6/questions.yml
- charts/portworx/v1.0.6/templates/NOTES.txt
- charts/portworx/v1.0.6/templates/_helpers.tpl
- charts/portworx/v1.0.6/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx/v1.0.6/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
- charts/portworx/v1.0.6/templates/portworx-controller.yaml
- charts/portworx/v1.0.6/templates/portworx-csi.yaml
- charts/portworx/v1.0.6/templates/portworx-ds.yaml
- charts/portworx/v1.0.6/templates/portworx-lighthouse.yaml
- charts/portworx/v1.0.6/templates/portworx-rbac-config.yaml
- charts/portworx/v1.0.6/templates/portworx-service.yaml
- charts/portworx/v1.0.6/templates/portworx-storageclasses.yaml
- charts/portworx/v1.0.6/templates/portworx-stork.yaml
- charts/portworx/v1.0.6/templates/serviceaccount-hook.yaml
- charts/portworx/v1.0.6/values.yaml
* Remove full FQDN to avoid custom cluster name
* update px image to 2.3.4 version
> px release 106

- charts/portworx/v1.0.7/Chart.yaml
- charts/portworx/v1.0.7/README.md
- charts/portworx/v1.0.7/app-readme.md
- charts/portworx/v1.0.7/ci/test-values.yaml
- charts/portworx/v1.0.7/questions.yml
- charts/portworx/v1.0.7/templates/NOTES.txt
- charts/portworx/v1.0.7/templates/_helpers.tpl
- charts/portworx/v1.0.7/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx/v1.0.7/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
- charts/portworx/v1.0.7/templates/portworx-controller.yaml
- charts/portworx/v1.0.7/templates/portworx-csi.yaml
- charts/portworx/v1.0.7/templates/portworx-ds.yaml
- charts/portworx/v1.0.7/templates/portworx-lighthouse.yaml
- charts/portworx/v1.0.7/templates/portworx-rbac-config.yaml
- charts/portworx/v1.0.7/templates/portworx-service.yaml
- charts/portworx/v1.0.7/templates/portworx-storageclasses.yaml
- charts/portworx/v1.0.7/templates/portworx-stork.yaml
- charts/portworx/v1.0.7/templates/serviceaccount-hook.yaml
- charts/portworx/v1.0.7/values.yaml
added portworx-api daemonSet, portworx namespace and roles
> px release 1.0.7

- charts/portworx/v1.0.7/questions.yml
Signed-off-by: trierra <oksana@portworx.com>
> hide the broken v1.0.7 from all rancher versions above 2.3.0

- charts/hpe-flexvolume-driver/v3.1.2/Chart.yaml
- charts/hpe-flexvolume-driver/v3.1.2/README.md
- charts/hpe-flexvolume-driver/v3.1.2/app-readme.md
- charts/hpe-flexvolume-driver/v3.1.2/questions.yml
- charts/hpe-flexvolume-driver/v3.1.2/templates/_helpers.tpl
- charts/hpe-flexvolume-driver/v3.1.2/templates/hpe-config.yaml
- charts/hpe-flexvolume-driver/v3.1.2/templates/hpe-doryd-rbac.yaml
- charts/hpe-flexvolume-driver/v3.1.2/templates/hpe-doryd.yaml
- charts/hpe-flexvolume-driver/v3.1.2/templates/hpe-flexvolume-plugin.yaml
- charts/hpe-flexvolume-driver/v3.1.2/templates/hpe-secret.yaml
- charts/hpe-flexvolume-driver/v3.1.2/templates/hpecv-cp.yaml
- charts/hpe-flexvolume-driver/v3.1.2/templates/post-install.yaml
- charts/hpe-flexvolume-driver/v3.1.2/templates/sc.yaml
- charts/hpe-flexvolume-driver/v3.1.2/values.yaml
- Fixed typo that prevented provisioner to find volume plugin socket in certain cases
- Fixed race condition between postStart and main container for flexvolume driver
> HPE FlexVolume Driver 3.1.2

- charts/portworx/v1.0.7/questions.yml
Signed-off-by: trierra <oksana@portworx.com>
> removed chart 1.0.7 from all rancher versions 

- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/Chart.yaml
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/README.md
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/app-readme.md
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/create-certs-for-cpx-istio-chart.sh
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/questions.yml
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/templates/cpx-sidecar-injector-configmap.yaml
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/templates/cpx-sidecar-injector-deployment-service.yaml
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/templates/cpx-sidecar-injector-emptyConfigMap.yaml
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/templates/cpx-sidecar-injector-serviceaccount.yaml
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/templates/cpx-sidecar-networkpolicy.yaml
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/templates/mutatingwebhook.yaml
- charts/citrix-cpx-istio-sidecar-injector/v1.2.0/values.yaml
Signed-off-by: Ajeeta Shakeet <ajeeta.shakeet@citrix.com>
> Adding Charts for Citrix ADC as sidecar in Istio Service-Mesh

- charts/citrix-adc-istio-ingress-gateway/v1.2.0/Chart.yaml
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/README.md
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/app-readme.md
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/questions.yml
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/templates/_helpers.tpl
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/templates/citrix-adc-ingressgateway-deployment.yaml
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/templates/ingressgateway-service.yaml
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/templates/metrics-exporter-service.yaml
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/templates/secret.yaml
- charts/citrix-adc-istio-ingress-gateway/v1.2.0/values.yaml
Signed-off-by: Ajeeta Shakeet <ajeeta.shakeet@citrix.com>
> Adding Charts for Citrix ADC as Ingress Gateway in Istio Service-Mesh

- charts/openebs/v1.7.0/Chart.yaml
- charts/openebs/v1.7.0/README.md
- charts/openebs/v1.7.0/app-readme.md
- charts/openebs/v1.7.0/questions.yml
- charts/openebs/v1.7.0/templates/NOTES.txt
- charts/openebs/v1.7.0/templates/_helpers.tpl
- charts/openebs/v1.7.0/templates/clusterrole.yaml
- charts/openebs/v1.7.0/templates/clusterrolebinding.yaml
- charts/openebs/v1.7.0/templates/cm-node-disk-manager.yaml
- charts/openebs/v1.7.0/templates/daemonset-ndm.yaml
- charts/openebs/v1.7.0/templates/deployment-admission-server.yaml
- charts/openebs/v1.7.0/templates/deployment-local-provisioner.yaml
- charts/openebs/v1.7.0/templates/deployment-maya-apiserver.yaml
- charts/openebs/v1.7.0/templates/deployment-maya-provisioner.yaml
- charts/openebs/v1.7.0/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/v1.7.0/templates/deployment-ndm-operator.yaml
- charts/openebs/v1.7.0/templates/psp-clusterrole.yaml
- charts/openebs/v1.7.0/templates/psp-clusterrolebinding.yaml
- charts/openebs/v1.7.0/templates/psp.yaml
- charts/openebs/v1.7.0/templates/service-maya-apiserver.yaml
- charts/openebs/v1.7.0/templates/serviceaccount.yaml
- charts/openebs/v1.7.0/values.yaml
Signed-off-by: prateekpandey14 <prateek.pandey@openebs.io>
> stable(openebs): update 1.7.0 release version

- charts/openebs/v1.8.0/Chart.yaml
- charts/openebs/v1.8.0/README.md
- charts/openebs/v1.8.0/app-readme.md
- charts/openebs/v1.8.0/questions.yml
- charts/openebs/v1.8.0/templates/NOTES.txt
- charts/openebs/v1.8.0/templates/_helpers.tpl
- charts/openebs/v1.8.0/templates/clusterrole.yaml
- charts/openebs/v1.8.0/templates/clusterrolebinding.yaml
- charts/openebs/v1.8.0/templates/cm-node-disk-manager.yaml
- charts/openebs/v1.8.0/templates/daemonset-ndm.yaml
- charts/openebs/v1.8.0/templates/deployment-admission-server.yaml
- charts/openebs/v1.8.0/templates/deployment-local-provisioner.yaml
- charts/openebs/v1.8.0/templates/deployment-maya-apiserver.yaml
- charts/openebs/v1.8.0/templates/deployment-maya-provisioner.yaml
- charts/openebs/v1.8.0/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/v1.8.0/templates/deployment-ndm-operator.yaml
- charts/openebs/v1.8.0/templates/psp-clusterrole.yaml
- charts/openebs/v1.8.0/templates/psp-clusterrolebinding.yaml
- charts/openebs/v1.8.0/templates/psp.yaml
- charts/openebs/v1.8.0/templates/service-maya-apiserver.yaml
- charts/openebs/v1.8.0/templates/serviceaccount.yaml
- charts/openebs/v1.8.0/values.yaml
>  stable(openebs): update 1.8.0 release version

- charts/openebs/v1.9.0/Chart.yaml
- charts/openebs/v1.9.0/README.md
- charts/openebs/v1.9.0/app-readme.md
- charts/openebs/v1.9.0/questions.yml
- charts/openebs/v1.9.0/templates/NOTES.txt
- charts/openebs/v1.9.0/templates/_helpers.tpl
- charts/openebs/v1.9.0/templates/clusterrole.yaml
- charts/openebs/v1.9.0/templates/clusterrolebinding.yaml
- charts/openebs/v1.9.0/templates/cm-node-disk-manager.yaml
- charts/openebs/v1.9.0/templates/daemonset-ndm.yaml
- charts/openebs/v1.9.0/templates/deployment-admission-server.yaml
- charts/openebs/v1.9.0/templates/deployment-local-provisioner.yaml
- charts/openebs/v1.9.0/templates/deployment-maya-apiserver.yaml
- charts/openebs/v1.9.0/templates/deployment-maya-provisioner.yaml
- charts/openebs/v1.9.0/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/v1.9.0/templates/deployment-ndm-operator.yaml
- charts/openebs/v1.9.0/templates/psp-clusterrole.yaml
- charts/openebs/v1.9.0/templates/psp-clusterrolebinding.yaml
- charts/openebs/v1.9.0/templates/psp.yaml
- charts/openebs/v1.9.0/templates/service-maya-apiserver.yaml
- charts/openebs/v1.9.0/templates/serviceaccount.yaml
- charts/openebs/v1.9.0/values.yaml
Updated README
Updated questions.yaml
Updated values.yaml
Update liveness checks in openebs deployments
> stable(openebs): update 1.9.0 release version 

- charts/neuvector/v1.5.1/Chart.yaml
- charts/neuvector/v1.5.1/README.md
- charts/neuvector/v1.5.1/app-readme.md
- charts/neuvector/v1.5.1/questions.yml
- charts/neuvector/v1.5.1/templates/NOTES.txt
- charts/neuvector/v1.5.1/templates/_helpers.tpl
- charts/neuvector/v1.5.1/templates/admission-webhook-service.yaml
- charts/neuvector/v1.5.1/templates/clusterrole.yaml
- charts/neuvector/v1.5.1/templates/clusterrolebinding.yaml
- charts/neuvector/v1.5.1/templates/configmap.yaml
- charts/neuvector/v1.5.1/templates/controller-deployment.yaml
- charts/neuvector/v1.5.1/templates/controller-service.yaml
- charts/neuvector/v1.5.1/templates/crd.yaml
- charts/neuvector/v1.5.1/templates/enforcer-daemonset.yaml
- charts/neuvector/v1.5.1/templates/exporter-deployment.yaml
- charts/neuvector/v1.5.1/templates/ingress.yaml
- charts/neuvector/v1.5.1/templates/manager-deployment.yaml
- charts/neuvector/v1.5.1/templates/manager-service.yaml
- charts/neuvector/v1.5.1/templates/psp.yaml
- charts/neuvector/v1.5.1/templates/pvc.yaml
- charts/neuvector/v1.5.1/templates/rolebinding.yaml
- charts/neuvector/v1.5.1/templates/route.yaml
- charts/neuvector/v1.5.1/templates/scanner-deployment.yaml
- charts/neuvector/v1.5.1/templates/secret.yaml
- charts/neuvector/v1.5.1/templates/updater-cronjob.yaml
- charts/neuvector/v1.5.1/values.yaml
Updating NeuVector Rancher Catalog with new version 1.5.1 of helm chart.
> Updating NeuVector Helm Chart

- charts/longhorn/latest/Chart.yaml
- charts/longhorn/latest/questions.yml
- charts/longhorn/latest/templates/default-setting.yaml
- charts/longhorn/latest/templates/deployment-driver.yaml
- charts/longhorn/latest/templates/deployment-ui.yaml
- charts/longhorn/latest/values.yaml
- charts/longhorn/v0.8.1/.helmignore
- charts/longhorn/v0.8.1/Chart.yaml
- charts/longhorn/v0.8.1/README.md
- charts/longhorn/v0.8.1/app-readme.md
- charts/longhorn/v0.8.1/questions.yml
- charts/longhorn/v0.8.1/templates/NOTES.txt
- charts/longhorn/v0.8.1/templates/_helpers.tpl
- charts/longhorn/v0.8.1/templates/clusterrole.yaml
- charts/longhorn/v0.8.1/templates/clusterrolebinding.yaml
- charts/longhorn/v0.8.1/templates/crds.yaml
- charts/longhorn/v0.8.1/templates/daemonset-sa.yaml
- charts/longhorn/v0.8.1/templates/default-setting.yaml
- charts/longhorn/v0.8.1/templates/deployment-driver.yaml
- charts/longhorn/v0.8.1/templates/deployment-ui.yaml
- charts/longhorn/v0.8.1/templates/ingress.yaml
- charts/longhorn/v0.8.1/templates/postupgrade-job.yaml
- charts/longhorn/v0.8.1/templates/registry-secret.yml
- charts/longhorn/v0.8.1/templates/serviceaccount.yaml
- charts/longhorn/v0.8.1/templates/storageclass.yaml
- charts/longhorn/v0.8.1/templates/tls-secrets.yaml
- charts/longhorn/v0.8.1/templates/uninstall-job.yaml
- charts/longhorn/v0.8.1/values.yaml
https://github.com/longhorn/longhorn/issues/1395
> Longhorn: v1.0.0 release

- charts/longhorn/latest/README.md
- charts/longhorn/latest/app-readme.md
https://github.com/rancher/rancher/issues/27423
https://github.com/longhorn/longhorn/issues/1454
Signed-off-by: Bo Tao <bo.tao@rancher.com>
> Longhorn: Add downgrade warning and highlight namespace requirement

- README.md
- packages/rancher-monitoring/package.yaml
- scripts/clean
- scripts/generate-charts
- scripts/generate-patch
- scripts/prepare
- scripts/prepare-crds
This PR is a continuation of https://github.com/rancher/dev-charts/pull/52.
It should address all the pending comments on the original PR.
> Add generateCRDChart flag

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/charts/values.yaml
Adding newest version of istio
Changing default values for components that should not be on during default install
> Update version to 1.6.7

- packages/rancher-logging/overlay/templates/logging-rke1.yaml
- packages/rancher-logging/rancher-logging.patch
This pr adds configuration for rke1 log aggregation.  By default rke 1 log aggregation is disabled.
> added rke support

- packages/rancher-logging/overlay/templates/userroles.yaml
closes https://github.com/rancher/rancher/issues/28256
> fixed logging cluster roles

- charts/instana-agent/v1.0.30/.helmignore
- charts/instana-agent/v1.0.30/Chart.yaml
- charts/instana-agent/v1.0.30/OWNERS
- charts/instana-agent/v1.0.30/README.md
- charts/instana-agent/v1.0.30/app-readme.md
- charts/instana-agent/v1.0.30/questions.yml
- charts/instana-agent/v1.0.30/templates/NOTES.txt
- charts/instana-agent/v1.0.30/templates/_helpers.tpl
- charts/instana-agent/v1.0.30/templates/agentsecret.yaml
- charts/instana-agent/v1.0.30/templates/clusterrole.yaml
- charts/instana-agent/v1.0.30/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.30/templates/configmap.yaml
- charts/instana-agent/v1.0.30/templates/daemonset.yaml
- charts/instana-agent/v1.0.30/templates/namespace.yaml
- charts/instana-agent/v1.0.30/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.30/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.30/values.yaml
Add support for PVC (persistentvolumes, persistentvolumeclaims) by adding `persistentvolumes` and `persistentvolumeclaims` clusterroles to the 'core' apiGroup
> Chart version 1.0.30

- charts/portworx-essentials/v1.0.1/Chart.yaml
- charts/portworx-essentials/v1.0.1/README.md
- charts/portworx-essentials/v1.0.1/app-readme.md
- charts/portworx-essentials/v1.0.1/ci/test-values.yaml
- charts/portworx-essentials/v1.0.1/questions.yml
- charts/portworx-essentials/v1.0.1/templates/NOTES.txt
- charts/portworx-essentials/v1.0.1/templates/_helpers.tpl
- charts/portworx-essentials/v1.0.1/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx-essentials/v1.0.1/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
- charts/portworx-essentials/v1.0.1/templates/portworx-controller.yaml
- charts/portworx-essentials/v1.0.1/templates/portworx-csi.yaml
- charts/portworx-essentials/v1.0.1/templates/portworx-ds.yaml
- charts/portworx-essentials/v1.0.1/templates/portworx-essential.yaml
- charts/portworx-essentials/v1.0.1/templates/portworx-rbac-config.yaml
- charts/portworx-essentials/v1.0.1/templates/portworx-service.yaml
- charts/portworx-essentials/v1.0.1/templates/portworx-storageclasses.yaml
- charts/portworx-essentials/v1.0.1/templates/portworx-stork.yaml
- charts/portworx-essentials/v1.0.1/templates/serviceaccount-hook.yaml
- charts/portworx-essentials/v1.0.1/values.yaml
Update the PX-Essentials chart to install
1. Portworx 2.5.6
2. Stork 2.4.3
> [Portworx] Update chart for Portworx Essentials to Release 2.5.6

- charts/portworx/v1.0.10/Chart.yaml
- charts/portworx/v1.0.10/README.md
- charts/portworx/v1.0.10/app-readme.md
- charts/portworx/v1.0.10/ci/test-values.yaml
- charts/portworx/v1.0.10/questions.yml
- charts/portworx/v1.0.10/templates/NOTES.txt
- charts/portworx/v1.0.10/templates/_helpers.tpl
- charts/portworx/v1.0.10/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx/v1.0.10/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
- charts/portworx/v1.0.10/templates/portworx-controller.yaml
- charts/portworx/v1.0.10/templates/portworx-csi.yaml
- charts/portworx/v1.0.10/templates/portworx-ds.yaml
- charts/portworx/v1.0.10/templates/portworx-lighthouse.yaml
- charts/portworx/v1.0.10/templates/portworx-rbac-config.yaml
- charts/portworx/v1.0.10/templates/portworx-service.yaml
- charts/portworx/v1.0.10/templates/portworx-storageclasses.yaml
- charts/portworx/v1.0.10/templates/portworx-stork.yaml
- charts/portworx/v1.0.10/templates/serviceaccount-hook.yaml
- charts/portworx/v1.0.10/values.yaml
Update the Portworx Enterprise chart to install
1. Portworx 2.5.6
2. Stork 2.4.3
> [Portworx] Update chart for Portworx Enterprise to Release 2.5.6

- packages/rancher-istio/charts/configs/istio-base.yaml
- packages/rancher-istio/charts/values.yaml
Update istio to version 1.7.0
Images mirrored: https://github.com/rancher/image-mirror/pull/23
> Istio version 1.7.0

- packages/rancher-istio/charts/Chart.yaml
Failed to update chart.yaml when increasing version. Upated from 1.6.8 to 1.7.0
> Correcting version in chart.yaml

- packages/rancher-monitoring/rancher-monitoring.patch
Only the second commit needs to be reviewed. The first commit just rearranges the patch due to an issue noted in https://github.com/rancher/rancher/issues/28627.
Related Issue: https://github.com/rancher/dashboard/issues/811
> Update default Alerting template for defaults set in UI

- packages/rancher-logging/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
> removed k3s syslog parser

- .github/workflows/push.yml
- scripts/generate-charts
Reverts rancher/charts#605
We'll redo this later
> Revert "Generate asset on different branch"

- scripts/generate-patch
Related Issue: https://github.com/rancher/rancher/issues/28981
> Allow trailing slashes in dependency repos

- packages/backup-restore-operator/charts/templates/s3-secret.yaml
- packages/backup-restore-operator/charts/values.yaml
The configuration fields in UI are populated with the default values, so removing these default values and setting them to empty values. Related to this bug https://github.com/rancher/dashboard/issues/1019#issuecomment-697098476
> Remove default values so they're not set while launching app

- packages/longhorn/longhorn.patch
- packages/longhorn/overlay/templates/userroles.yaml
- packages/longhorn/package.yaml
This PR is from #526
Issue: rancher/rancher#27725
> Longhorn: Add upstream Longhorn chart

- packages/rancher-monitoring/rancher-monitoring.patch
Just a quick change to the defaults for the `values.yaml`.
Related Issue: https://github.com/rancher/rancher/issues/29165
> Enable anonymous auth for Grafana

- packages/rancher-backup/charts/Chart.yaml
https://github.com/rancher/dashboard/issues/1438
> Add annotation to make chart available only in local cluster

- packages/rancher-backup/charts/templates/rancher-resourceset.yaml
https://github.com/rancher/backup-restore-operator/issues/30
Kinds and KindsRegexp fields can accept both the actual Kind (singular camelcase) or resource (plural)
> Update rancher resource set

- packages/rancher-monitoring/rancher-monitoring.patch
Related Issue: https://github.com/rancher/rancher/issues/29165
> Change default anonymous user on Grafana from Editor to Viewer

- packages/rancher-cis-benchmark/charts/README.md
Adding some detail to readme to regenerate the chart assets
https://github.com/rancher/cis-operator/issues/37
> Add some more detail to readme

- packages/rancher-webhook/package.yaml
https://github.com/rancher/rancher/issues/29263
> Bump webhook

- packages/rancher-logging/rancher-logging.patch
https://github.com/rancher/rancher/issues/29297
> added tolerations for rke controlplane/etcd nodes

- .github/workflows/pull_request_template.md
Related Issue: https://github.com/rancher/rancher/issues/29446
> Add PR template

- packages/longhorn/package.yaml
- packages/rancher-backup/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-gatekeeper/package.yaml
- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-kiali-server/package.yaml
- packages/rancher-logging/package.yaml
- packages/rancher-monitoring/package.yaml
- scripts/produce-sha256
part of: https://github.com/rancher/rancher/issues/29219
> Increment chart versions for new changes

- charts/instana-agent/v1.0.31/.helmignore
- charts/instana-agent/v1.0.31/Chart.yaml
- charts/instana-agent/v1.0.31/OWNERS
- charts/instana-agent/v1.0.31/README.md
- charts/instana-agent/v1.0.31/app-readme.md
- charts/instana-agent/v1.0.31/questions.yml
- charts/instana-agent/v1.0.31/templates/NOTES.txt
- charts/instana-agent/v1.0.31/templates/_helpers.tpl
- charts/instana-agent/v1.0.31/templates/agentsecret.yaml
- charts/instana-agent/v1.0.31/templates/clusterrole.yaml
- charts/instana-agent/v1.0.31/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.31/templates/configmap.yaml
- charts/instana-agent/v1.0.31/templates/daemonset.yaml
- charts/instana-agent/v1.0.31/templates/namespace.yaml
- charts/instana-agent/v1.0.31/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.31/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.31/values.yaml
- Introducing the option to configure and report to multiple Instana backends
- Additional documentation and cleanup on the README
> [instana-agent] Chart version 1.0.31

- charts/openebs/v1.12.0/Chart.yaml
- charts/openebs/v1.12.0/README.md
- charts/openebs/v1.12.0/app-readme.md
- charts/openebs/v1.12.0/questions.yml
- charts/openebs/v1.12.0/templates/NOTES.txt
- charts/openebs/v1.12.0/templates/_helpers.tpl
- charts/openebs/v1.12.0/templates/clusterrole.yaml
- charts/openebs/v1.12.0/templates/clusterrolebinding.yaml
- charts/openebs/v1.12.0/templates/cm-node-disk-manager.yaml
- charts/openebs/v1.12.0/templates/daemonset-ndm.yaml
- charts/openebs/v1.12.0/templates/deployment-admission-server.yaml
- charts/openebs/v1.12.0/templates/deployment-local-provisioner.yaml
- charts/openebs/v1.12.0/templates/deployment-maya-apiserver.yaml
- charts/openebs/v1.12.0/templates/deployment-maya-provisioner.yaml
- charts/openebs/v1.12.0/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/v1.12.0/templates/deployment-ndm-operator.yaml
- charts/openebs/v1.12.0/templates/psp-clusterrole.yaml
- charts/openebs/v1.12.0/templates/psp-clusterrolebinding.yaml
- charts/openebs/v1.12.0/templates/psp.yaml
- charts/openebs/v1.12.0/templates/service-maya-apiserver.yaml
- charts/openebs/v1.12.0/templates/serviceaccount.yaml
- charts/openebs/v1.12.0/values.yaml
- Remove hardcoded admission deployment imagePullPolicy 
- Add support to admission server to use hostNetwork 
- Add webhook failure policy configurable env
> stable(openebs): update 1.12.0 release version

- packages/rancher-istio/charts/README.md
- packages/rancher-istio/charts/app-readme.md
- packages/rancher-istio/charts/values.yaml
**Problem**
- Need to update to include grafana dashboard changes
- Kiali dependencies is still not very clear and inconsistency in capitalization 
**Solution**
- Need to bump installer version to add the grafana dashboard changes
- Updated readme to make some clarifications for the kiali dependencies, and added consistent capitalization. 
**Issues**
https://github.com/rancher/rancher/issues/28468
https://github.com/rancher/rancher/issues/29418
**Additional Info**
Since rancher-istio 1.7.3 chart is not in production, not bumping version - will just overwrite existing dev chart
> Bump image version

- packages/rancher-istio/charts/app-readme.md
No version bump is needed if this gets into 2.5.2 as Istio 1.7.3 was already added.
> rearranged istio app-readme

- packages/rancher-backup/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-gatekeeper/rancher-gatekeeper.patch
- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-logging/rancher-logging.patch
- packages/rancher-monitoring/rancher-monitoring.patch
- packages/rio/charts/Chart.yaml
https://github.com/rancher/rancher/issues/29934
> Adds display-name annotation

- scripts/generate-charts
Related Issue: https://github.com/rancher/rancher/issues/29064
> Add cleanup steps to make charts

- packages/rancher-logging/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/rancher-logging.patch
Relevant Issues:
- rancher/rancher#28573
- rancher/rancher#28574
```
[x] AKS
[x] GKE
```
> Add base cloud logging contents for AKS and GKE

- packages/rancher-tracing/charts/values.yaml
**Problem**
Original image existed in chart causing errors on chart scan
**Solution**
Change repository image to rancher mirrored image
**Related PRs**
https://github.com/rancher/charts/pull/850
**Issue**
https://github.com/rancher/rancher/issues/29903
> Change repository to rancher image

- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-rke2-cis-1.5-hardened.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-rke2-cis-1.5-permissive.yaml
- packages/rancher-cis-benchmark/charts/templates/configmap.yaml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-rke2-cis-1.5-hardened.yml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-rke2-cis-1.5-permissive.yml
- packages/rancher-cis-benchmark/charts/values.yaml
Add support for RKE2.
Reference issue: https://github.com/rancher/rke2/issues/1
Added a ticket under cis-operator  for tracking these changes: https://github.com/rancher/cis-operator/issues/59
> add rke2 as scan target

- charts/openebs/v2.2.0/Chart.yaml
- charts/openebs/v2.2.0/README.md
- charts/openebs/v2.2.0/app-readme.md
- charts/openebs/v2.2.0/questions.yml
- charts/openebs/v2.2.0/templates/NOTES.txt
- charts/openebs/v2.2.0/templates/_helpers.tpl
- charts/openebs/v2.2.0/templates/clusterrole.yaml
- charts/openebs/v2.2.0/templates/clusterrolebinding.yaml
- charts/openebs/v2.2.0/templates/cm-node-disk-manager.yaml
- charts/openebs/v2.2.0/templates/daemonset-ndm.yaml
- charts/openebs/v2.2.0/templates/deployment-admission-server.yaml
- charts/openebs/v2.2.0/templates/deployment-local-provisioner.yaml
- charts/openebs/v2.2.0/templates/deployment-maya-apiserver.yaml
- charts/openebs/v2.2.0/templates/deployment-maya-provisioner.yaml
- charts/openebs/v2.2.0/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/v2.2.0/templates/deployment-ndm-operator.yaml
- charts/openebs/v2.2.0/templates/psp-clusterrole.yaml
- charts/openebs/v2.2.0/templates/psp-clusterrolebinding.yaml
- charts/openebs/v2.2.0/templates/psp.yaml
- charts/openebs/v2.2.0/templates/service-maya-apiserver.yaml
- charts/openebs/v2.2.0/templates/serviceaccount.yaml
- charts/openebs/v2.2.0/values.yaml
Update to v2.2.0 release, 
Update to v2.1.0  and v2.0.0 release, 
- Updated questions.yaml to point the NDM images instead of defaults to quay.io
> stable(openebs): update v2.2.0 release version 

- packages/fleet-agent/package.yaml
- packages/fleet-crd/package.yaml
- packages/fleet/package.yaml
New tag for fleet to test https://github.com/rancher/fleet/pull/169
> Update fleet to v0.3.2-rc3

- packages/rancher-external-ip-webhook/package.yaml
- packages/rancher-external-ip-webhook/rancher-external-ip-webhook.patch
Related to https://github.com/rancher/rancher/issues/30424
> [2.5] Updated rancher-external-ip-webhook enhanced questions and README

- packages/rancher-logging/rancher-logging.patch
Relevant issue: https://github.com/rancher/rancher/issues/30450
> Add catalog.cattle.io/os linux annotation to logging

- packages/rancher-gatekeeper/rancher-gatekeeper.patch
https://github.com/rancher/rancher/issues/30450
> Add catalog.cattle.io/os=linux to rancher-gatekeeper

- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/crds/clusterscan.yaml
- packages/rancher-cis-benchmark/charts/crds/clusterscanbenchmark.yaml
- packages/rancher-cis-benchmark/charts/templates/deployment.yaml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-rke-1.5-hardened.yml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-rke-1.5-permissive.yml
- packages/rancher-cis-benchmark/charts/values.yaml
This is the corresponding charts PR for cis-operator changes https://github.com/rancher/cis-operator/pull/72
https://github.com/rancher/cis-operator/issues/60
https://github.com/rancher/security-scan/issues/28
https://github.com/rancher/security-scan/issues/29
https://github.com/rancher/rancher/issues/30450
> CIS v2 Chart changes

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-kiali-server/package.yaml
- packages/rancher-kiali-server/rancher-kiali-server.patch
- packages/rancher-tracing/charts/Chart.yaml
https://github.com/rancher/rancher/issues/30450
> Add linux annotation to istio packages

- packages/rancher-cis-benchmark/charts/templates/cis-roles.yaml
- packages/rancher-cis-benchmark/charts/templates/deployment.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
https://github.com/rancher/cis-operator/issues/71
Pass on alerts.enabled flag:
https://github.com/rancher/cis-operator/issues/76
@cbron @mrajashree Also updated the cis-operator image tag and security-scan image tag, need a re-review
> CIS rbac changes as required by Dashboard UI, Also pass the alerts.enabled flag to operator

- packages/longhorn/longhorn.patch
- packages/longhorn/overlay/templates/userroles.yaml
- packages/longhorn/package.yaml
longhorn/longhorn#2061
https://github.com/longhorn/longhorn/issues/1829
> Longhorn: v1.1.0 release for Rancher v2.5 Chart

- packages/rancher-logging/overlay/app-readme.md
Just a way to re-generate a package.
> bump logging

- packages/longhorn/longhorn.patch
- packages/longhorn/overlay/templates/userroles.yaml
- packages/longhorn/package.yaml
> Revert "Longhorn: v1.1.0 release for Rancher v2.5 Chart"

- packages/rancher-logging/overlay/templates/loggings/rke/daemonset.yaml
Relevant Issues:
- https://github.com/rancher/rancher/issues/30595
- https://github.com/rancher/rancher/issues/30809
> Fix hostPath type for logging rke

- packages/rancher-logging/generated-changes/patch/Chart.yaml.patch
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
- packages/rancher-logging/templates/crd-template/Chart.yaml
Relevant Issue: https://github.com/rancher/rancher/issues/30917
Image Mirror PR: https://github.com/rancher/image-mirror/pull/65
> Update logging chart to upstream 3.9.0

- packages/rancher-logging/generated-changes/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/logging-rke.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-journald.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Add PodSecurityPolicies for rancher-logging.
Addresses https://github.com/rancher/rancher/issues/30771
Original PR before charts changeover: https://github.com/rancher/charts/pull/931
> Add PodSecurityPolicies for rancher-logging

- packages/rancher-operator-crd/package.yaml
- packages/rancher-operator/package.yaml
rancher-operator PR:
https://github.com/rancher/rancher-operator/pull/17
> Update rancher-operator to v0.1.3-rc1

- packages/rancher-logging/generated-changes/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/logging-rke.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-journald.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Relevant issue: https://github.com/rancher/rancher/issues/31006
Original issue: https://github.com/rancher/rancher/issues/30771
> [Logging v2] Split psp settings for logging

- packages/rancher-monitoring/generated-changes/patch/Chart.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/charts/prometheus-node-exporter/values.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/templates/prometheus/prometheus.yaml.patch
- packages/rancher-monitoring/package.yaml
- packages/rancher-pushprox/charts/templates/_helpers.tpl
- packages/rancher-pushprox/package.yaml
Related Issues: https://github.com/rancher/rancher/issues/30712, https://github.com/rancher/rancher/issues/30191, https://github.com/rancher/rancher/issues/30684, https://github.com/rancher/rancher/issues/30680
> Minor fixes for Monitoring v2

- scripts/pull-scripts
vendors https://github.com/rancher/charts-build-scripts/pull/10
> Bump scripts version to v0.0.3

- packages/rancher-logging/generated-changes/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/logging-rke.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-journald.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Relevant issue: https://github.com/rancher/rancher/issues/30329
> [Logging v2] Default to the global mountPath for logging vendors

- packages/rancher-operator-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator-crd/package.yaml
- packages/rancher-operator/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator/package.yaml
https://github.com/rancher/rancher/issues/29993
> update rancher-operator to v0.1.3-rc4

- packages/rancher-logging/generated-changes/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/logging-rke.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-journald.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Add fluentbit and fluentd resources to logging. Add clearer comments on
the two psp settings.
Relevant issue: https://github.com/rancher/rancher/issues/31099
> Add fluent resources to logging

- packages/fleet-agent/generated-changes/patch/Chart.yaml.patch
- packages/fleet-agent/package.yaml
- packages/fleet-crd/generated-changes/patch/Chart.yaml.patch
- packages/fleet-crd/package.yaml
- packages/fleet/generated-changes/patch/Chart.yaml.patch
- packages/fleet/package.yaml
Relevant issue: https://github.com/rancher/rancher/issues/30516
> Update fleet to v0.3.4-rc3

- packages/rancher-backup/charts/Chart.yaml
- packages/rancher-cis-benchmark/templates/crd-template/Chart.yaml
Tied to merge of https://github.com/rancher/charts/pull/975 first in order to remove the currently existing assets.
> Remove packageVersion from Backups and CIS

- index.yaml
This should have been done as part of https://github.com/rancher/charts/pull/975, but was a missed step.
Related Issue: https://github.com/rancher/rancher/issues/31137
> Remove broken versions from index.yaml

- .gitignore
- Makefile
- README.md
- _config.yml
- scripts/pull-scripts
- scripts/version
Autogenerated from `make docs` + adding a `./scripts.version` manually
> [Live] Bump version to v0.0.4

- .gitignore
- Makefile
- README.md
- released/README.md
- scripts/pull-scripts
- scripts/release-assets
- scripts/version
Autogenerated from `make docs` + adding a `./scripts.version` manually
> [Staging] Bump version to v0.0.4

- Makefile
- README.md
- scripts/pull-scripts
- scripts/version
Autogenerated from `make docs` + adding a `./scripts.version` manually
> [Source] Bump version to v0.0.4

- packages/rancher-operator-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator-crd/package.yaml
- packages/rancher-operator/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator/package.yaml
Issue: https://github.com/rancher/rancher/issues/30047
> [dev-v2.5-source-alt] Update rancher-operator to rc5

- packages/fleet-agent/generated-changes/patch/Chart.yaml.patch
- packages/fleet-agent/package.yaml
- packages/fleet-crd/generated-changes/patch/Chart.yaml.patch
- packages/fleet-crd/package.yaml
- packages/fleet/generated-changes/patch/Chart.yaml.patch
- packages/fleet/package.yaml
Note: this may change to be merged into `dev-v2.5-source` pending @aiyengar2.
Relevant issue: https://github.com/rancher/rancher/issues/30516
> Update fleet to v0.3.4-rc4

- packages/fleet-agent/generated-changes/patch/Chart.yaml.patch
- packages/fleet-agent/package.yaml
- packages/fleet-crd/generated-changes/patch/Chart.yaml.patch
- packages/fleet-crd/package.yaml
- packages/fleet/generated-changes/patch/Chart.yaml.patch
- packages/fleet/package.yaml
Relevant issue: rancher/rancher#30516
Relevant PR: https://github.com/rancher/fleet/pull/276
> Update fleet to v0.3.4-rc5

- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/logging-rke.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/validate-install.yaml
- packages/rancher-logging/package.yaml
Relevant issue: https://github.com/rancher/rancher/issues/30329
> [Logging v2] Add extraVolumeMounts to dockerRootDir

- packages/rancher-monitoring/generated-changes/patch/templates/_helpers.tpl.patch
- packages/rancher-monitoring/generated-changes/patch/templates/exporters/kubelet/servicemonitor.yaml.patch
- packages/rancher-monitoring/package.yaml
Related Issue: https://github.com/rancher/rancher/issues/31167, https://github.com/rancher/rancher/issues/31305
> Update default kubelet path for k8s 1.20

- packages/longhorn/generated-changes/patch/values.yaml.patch
- packages/longhorn/package.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
- packages/rancher-cis-benchmark/package.yaml
- packages/rancher-gatekeeper/generated-changes/patch/values.yaml.patch
- packages/rancher-gatekeeper/package.yaml
- packages/rancher-istio/charts/values.yaml
- packages/rancher-istio/package.yaml
- packages/rancher-kiali-server/generated-changes/patch/values.yaml.patch
- packages/rancher-kiali-server/package.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
- packages/rancher-monitoring/generated-changes/patch/charts/grafana/values.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/charts/kube-state-metrics/values.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/charts/prometheus-adapter/values.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/charts/prometheus-node-exporter/values.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/values.yaml.patch
- packages/rancher-monitoring/package.yaml
- packages/rancher-pushprox/charts/values.yaml
- packages/rancher-pushprox/package.yaml
- packages/rancher-tracing/charts/values.yaml
- packages/rancher-tracing/package.yaml
Issue:
https://github.com/rancher/rancher/issues/30888
> Add 'mirrored-' to mirrored charts for 2.5.6

- packages/rancher-operator-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator-crd/package.yaml
- packages/rancher-operator/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator/package.yaml
https://github.com/rancher/rancher/issues/31236
> update rancher-operator v0.1.3-rc6

- packages/rancher-external-ip-webhook/generated-changes/patch/values.yaml.patch
- packages/rancher-external-ip-webhook/package.yaml
**Issue:**
https://github.com/rancher/rancher/issues/30888
> Update repo to rancher/mirrored-kube-rbac-proxy

- packages/rancher-operator-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator-crd/package.yaml
- packages/rancher-operator/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator/package.yaml
https://github.com/rancher/rancher/issues/29993
> update rancher-operator v0.1.3-rc7

- packages/vsphere-cpi/charts/Chart.yaml
- packages/vsphere-cpi/package.yaml
- packages/vsphere-csi/charts/Chart.yaml
- packages/vsphere-csi/package.yaml
> Fix naming of CPI and CSI charts in Explorer

- packages/rancher-monitoring/package.yaml
- packages/rancher-pushprox/charts/Chart.yaml
- packages/rancher-pushprox/charts/templates/_helpers.tpl
- packages/rancher-pushprox/charts/templates/pushprox-clients.yaml
- packages/rancher-pushprox/charts/templates/pushprox-proxy.yaml
- packages/rancher-pushprox/package.yaml
Related Issue: https://github.com/rancher/rancher/issues/28327, https://github.com/rancher/rancher/issues/31498
> Add windows nodeSelector and tolerations to rancher-pushprox

- packages/rancher-monitoring/generated-changes/overlay/templates/alertmanager/cleanupSecret.yaml
- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/hardened.yaml
- packages/rancher-monitoring/generated-changes/patch/charts/grafana/templates/_pod.tpl.patch
- packages/rancher-monitoring/generated-changes/patch/charts/kube-state-metrics/templates/deployment.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/charts/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/charts/prometheus-node-exporter/templates/daemonset.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/templates/_helpers.tpl.patch
- packages/rancher-monitoring/generated-changes/patch/templates/alertmanager/alertmanager.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/templates/alertmanager/secret.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/templates/prometheus-operator/deployment.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/templates/prometheus/prometheus.yaml.patch
- packages/rancher-monitoring/package.yaml
- packages/rancher-monitoring/templates/crd-template/templates/_helpers.tpl
- packages/rancher-monitoring/templates/crd-template/templates/jobs.yaml
Related Issue: https://github.com/rancher/rancher/issues/28327, https://github.com/rancher/rancher/issues/31498, https://github.com/rancher/rancher/issues/31497
> Add windows nodeSelectors and tolerations to rancher-monitoring

- packages/fleet-agent/generated-changes/patch/Chart.yaml.patch
- packages/fleet-agent/package.yaml
- packages/fleet-crd/generated-changes/patch/Chart.yaml.patch
- packages/fleet-crd/package.yaml
- packages/fleet/generated-changes/patch/Chart.yaml.patch
- packages/fleet/package.yaml
Relevant issue: https://github.com/rancher/fleet/issues/311
> Update fleet charts to v0.3.5-rc1

- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/Chart.yaml
- packages/rancher-windows-exporter/package.yaml
Related Issue: https://github.com/rancher/rancher/issues/31740
> Hide windows-exporter

- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/templates/_helpers.tpl
- packages/rancher-windows-exporter/charts/templates/servicemonitor.yaml
- packages/rancher-windows-exporter/package.yaml
Related Issue: https://github.com/rancher/rancher/issues/31832
> Change rancher-windows-exporter job label to windows-exporter

- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/Chart.yaml.patch
- packages/rancher-logging/generated-changes/patch/README.md.patch
- packages/rancher-logging/generated-changes/patch/templates/deployment.yaml.patch
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
- packages/rancher-logging/templates/crd-template/Chart.yaml
- https://github.com/rancher/rancher/issues/31644
- https://github.com/rancher/rancher/issues/28721
> Update logging to 3.9.4 and add Windows support

- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Relevant issue: https://github.com/rancher/rancher/issues/31925
> Fix missing windows enabled value in logging

- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
- https://github.com/rancher/dashboard/issues/2626
- https://github.com/rancher/rancher/issues/28721
- https://github.com/rancher/rancher/issues/31644
> Use global.cattle instead of global for windows logging

- packages/fleet-agent/generated-changes/patch/Chart.yaml.patch
- packages/fleet-agent/package.yaml
- packages/fleet-crd/generated-changes/patch/Chart.yaml.patch
- packages/fleet-crd/package.yaml
- packages/fleet/generated-changes/patch/Chart.yaml.patch
- packages/fleet/package.yaml
Relevant issue: https://github.com/rancher/fleet/issues/324
> Update fleet charts to v0.3.5-rc2

- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
- packages/rancher-cis-benchmark/package.yaml
Updating cis-operator image tag to release this fix: https://github.com/rancher/cis-operator/issues/78
Also bumped the appVersion to v1.0.4
> Update cis-operator image tag and appVersion

- packages/fleet-agent/generated-changes/patch/Chart.yaml.patch
- packages/fleet-agent/package.yaml
- packages/fleet-crd/generated-changes/patch/Chart.yaml.patch
- packages/fleet-crd/package.yaml
- packages/fleet/generated-changes/patch/Chart.yaml.patch
- packages/fleet/package.yaml
Relevant issue: https://github.com/rancher/fleet/issues/287
> Update fleet charts to v0.3.5-rc3

- packages/rancher-operator-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator-crd/package.yaml
- packages/rancher-operator/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator/package.yaml
Issue:
https://github.com/rancher/rancher/issues/31954
> Add patch for rancher-operator 0.2.0-alpha02

- packages/rancher-monitoring/package.yaml
- packages/rancher-monitoring/templates/crd-template/templates/jobs.yaml
Related Issue: https://github.com/rancher/rancher/issues/31991, https://github.com/rancher/rancher/issues/31994
> Fix CRD chart

- packages/rancher-monitoring/generated-changes/patch/values.yaml.patch
- packages/rancher-monitoring/package.yaml
- packages/rancher-prometheus-adapter/generated-changes/patch/values.yaml.patch
- packages/rancher-prometheus-adapter/package.yaml
Related Issue: https://github.com/rancher/rancher/issues/29871
> Change adapter repo and remove from top-level values.yaml

- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/dashboards/rancher/default-dashboard.yaml
- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/dashboards/rancher/windows-dashboards.yaml
- packages/rancher-monitoring/generated-changes/patch/Chart.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/values.yaml.patch
- packages/rancher-monitoring/package.yaml
Related Issue: https://github.com/rancher/rancher/issues/31942
> Use global.cattle.windows.enabled for windowsExporter and deprecate windowsExporter.enabled

- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/package.yaml
- https://github.com/rancher/rancher/issues/28721
- https://github.com/rancher/rancher/issues/32021
> Add RKE node logs for Windows logging

- packages/rancher-webhook/generated-changes/patch/Chart.yaml.patch
- packages/rancher-webhook/package.yaml
Issue:
https://github.com/rancher/rancher/issues/31974
> Bump rancher-webhook to v0.1.0-rc1

- packages/rancher-operator-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator-crd/package.yaml
- packages/rancher-operator/generated-changes/patch/Chart.yaml.patch
- packages/rancher-operator/package.yaml
Related issue:
https://github.com/rancher/rancher/issues/31120
> Bump rancher-operator to v0.2.0-alpha03

- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/scripts/check-wins-version.ps1
- packages/rancher-windows-exporter/charts/scripts/run.ps1
- packages/rancher-windows-exporter/charts/templates/configmap.yaml
- packages/rancher-windows-exporter/charts/templates/daemonset.yaml
- packages/rancher-windows-exporter/charts/templates/servicemonitor.yaml
- packages/rancher-windows-exporter/package.yaml
- packages/rancher-wins-upgrader/generated-changes/patch/Chart.yaml.patch
- packages/rancher-wins-upgrader/package.yaml
Related Issues: https://github.com/rancher/rancher/issues/31827, https://github.com/rancher/rancher/issues/31842, https://github.com/rancher/rancher/issues/31927, https://github.com/rancher/rancher/issues/31953
> Minor updates around windows-exporter and wins upgrades

- packages/rancher-cis-benchmark/charts/templates/configmap.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
- packages/rancher-cis-benchmark/package.yaml
issue : https://github.com/rancher/rke2/issues/350
> Set min version rke2 and update security-scans version

- packages/rancher-istio-1.8/charts/Chart.yaml
- packages/rancher-istio-1.8/charts/values.yaml
- packages/rancher-istio-1.8/package.yaml
- packages/rancher-istio-1.9/charts/Chart.yaml
- packages/rancher-istio-1.9/charts/values.yaml
- packages/rancher-istio-1.9/package.yaml
Adding newest Istio versions for 1.8 and 1.9
> Add istio v1.8.5 & v1.9.3

- .github/workflows/push.yaml
Blocked on https://github.com/rancher/charts/pull/1136.
Related Issue: https://github.com/rancher/rancher/issues/32146
> [2.6] Add stage-release workflow

- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Relevant issues: 
- https://github.com/rancher/rancher/issues/32290
- https://github.com/rancher/rancher/issues/32016
**Note:** this PR is ready for review, but it requires https://github.com/rancher/rancher/pull/32291 to be merged first.
> Add os field for logging Windows image

- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/templates/_helpers.tpl.patch
- packages/rancher-logging/package.yaml
- https://github.com/rancher/rancher/issues/32320
- https://github.com/rancher/rancher/issues/32264
> Fix Windows optional flag for logging

- packages/rancher-backup-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-backup-crd/package.yaml
- packages/rancher-backup/generated-changes/patch/Chart.yaml.patch
- packages/rancher-backup/package.yaml
Issue: https://github.com/rancher/backup-restore-operator/issues/95
bump rancher-backup to 1.0.4-rc4
> bump rancher-backup to 1.0.4-rc4

- packages/rancher-eks-operator-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-eks-operator-crd/package.yaml
- packages/rancher-eks-operator/generated-changes/patch/Chart.yaml.patch
- packages/rancher-eks-operator/package.yaml
Issue:
https://github.com/rancher/rancher/issues/32293
> Add eks-operator

- packages/fleet-agent/generated-changes/patch/Chart.yaml.patch
- packages/fleet-agent/package.yaml
- packages/fleet-crd/generated-changes/patch/Chart.yaml.patch
- packages/fleet-crd/package.yaml
- packages/fleet/generated-changes/patch/Chart.yaml.patch
- packages/fleet/package.yaml
Relevant issue: https://github.com/rancher/fleet/issues/345
> Update fleet charts to v0.3.5-rc8

- packages/rancher-cis-benchmark/charts/values.yaml
- packages/rancher-cis-benchmark/package.yaml
this pr updates cis-operator and security-scans versions to include fixes for k3s-cis scans
issue: https://github.com/k3s-io/k3s/issues/1504 , https://github.com/rancher/rancher/issues/32428
> update cis-operator and security-scans versions

- packages/longhorn/generated-changes/exclude/templates/crds.yaml
- packages/longhorn/generated-changes/overlay/crds/crds.yaml
- packages/longhorn/generated-changes/overlay/templates/userroles.yaml
- packages/longhorn/generated-changes/patch/Chart.yaml.patch
- packages/longhorn/generated-changes/patch/README.md.patch
- packages/longhorn/generated-changes/patch/questions.yml.patch
- packages/longhorn/generated-changes/patch/values.yaml.patch
- packages/longhorn/package.yaml
- packages/longhorn/templates/crd-template/Chart.yaml
Longhorn v1.1.1 dev 2.5
Signed-off-by: Clark Hsu <clark.hsu@suse.com>
> Longhorn v1.1.1 release for branch "dev-v2.5-source"

- packages/rancher-cis-benchmark/charts/values.yaml
- packages/rancher-cis-benchmark/package.yaml
This pr updates the version of rancher/security scans to include a fix for https://github.com/k3s-io/k3s/issues/3248
> update rancher/seurity-scans v0.2.3-rc6

- packages/rancher-monitoring/package.yaml
- packages/rancher-monitoring/templates/crd-template/templates/jobs.yaml
Related Issue: https://github.com/rancher/rancher/issues/32499
> Preserve structural schema during preserveUnknownFields step if possible

- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/templates/_helpers.tpl
- packages/rancher-windows-exporter/charts/templates/daemonset.yaml
- packages/rancher-windows-exporter/charts/values.yaml
- packages/rancher-windows-exporter/package.yaml
- packages/rancher-wins-upgrader/package.yaml
Wins PR: https://github.com/rancher/wins/pull/37
Related Issue: https://github.com/rancher/rancher/issues/32194
> Use backslashes for windows_exporter and bump wins-upgrader

- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/scripts/check-wins-version.ps1
- packages/rancher-windows-exporter/charts/scripts/run.ps1
- packages/rancher-windows-exporter/charts/templates/daemonset.yaml
- packages/rancher-windows-exporter/charts/templates/rbac.yaml
- packages/rancher-windows-exporter/charts/values.yaml
- packages/rancher-windows-exporter/package.yaml
- packages/rancher-wins-upgrader/package.yaml
Wins PR: https://github.com/rancher/wins/pull/40
Related Issue: https://github.com/rancher/rancher/issues/32194#issuecomment-832287457
> Make all C: references c:

- packages/rancher-wins-upgrader/package.yaml
Related Issue: https://github.com/rancher/rancher/issues/32538
> Bump wins upgrader

- packages/rancher-vsphere-csi/charts/Chart.yaml
- packages/rancher-vsphere-csi/charts/README.md
- packages/rancher-vsphere-csi/charts/app-readme.md
- packages/rancher-vsphere-csi/charts/questions.yaml
- packages/rancher-vsphere-csi/charts/templates/_helpers.tpl
- packages/rancher-vsphere-csi/charts/templates/vsphere-csi-controller-deployment.yaml
- packages/rancher-vsphere-csi/charts/templates/vsphere-csi-controller-rbac.yaml
- packages/rancher-vsphere-csi/charts/templates/vsphere-csi-node-ds.yaml
- packages/rancher-vsphere-csi/charts/templates/vsphere-csi-node-rbac.yaml
- packages/rancher-vsphere-csi/charts/templates/vsphere-csi-secret.yaml
- packages/rancher-vsphere-csi/charts/templates/vsphere-csi-storageclass.yaml
- packages/rancher-vsphere-csi/charts/values.yaml
- packages/rancher-vsphere-csi/package.yaml
Issue: https://github.com/rancher/rancher/issues/31105
> [2.6] Update vsphere CSI to v2.2.0

- index.yaml
Some merge conflicts got resolved incorrectly leaving the index.yaml messed up. 
This pr deletes and recreates the index.yaml
> Recreate index.yaml

- charts/longhorn/latest/.helmignore
- charts/longhorn/latest/Chart.yaml
- charts/longhorn/latest/README.md
- charts/longhorn/latest/questions.yml
- charts/longhorn/latest/templates/default-setting.yaml
- charts/longhorn/latest/templates/tls-secrets.yaml
- charts/longhorn/latest/values.yaml
- charts/longhorn/v1.1.1/Chart.yaml
- charts/longhorn/v1.1.1/README.md
- charts/longhorn/v1.1.1/app-readme.md
- charts/longhorn/v1.1.1/questions.yml
- charts/longhorn/v1.1.1/templates/NOTES.txt
- charts/longhorn/v1.1.1/templates/_helpers.tpl
- charts/longhorn/v1.1.1/templates/clusterrole.yaml
- charts/longhorn/v1.1.1/templates/clusterrolebinding.yaml
- charts/longhorn/v1.1.1/templates/crds.yaml
- charts/longhorn/v1.1.1/templates/daemonset-sa.yaml
- charts/longhorn/v1.1.1/templates/default-setting.yaml
- charts/longhorn/v1.1.1/templates/deployment-driver.yaml
- charts/longhorn/v1.1.1/templates/deployment-ui.yaml
- charts/longhorn/v1.1.1/templates/ingress.yaml
- charts/longhorn/v1.1.1/templates/postupgrade-job.yaml
- charts/longhorn/v1.1.1/templates/psp.yaml
- charts/longhorn/v1.1.1/templates/registry-secret.yml
- charts/longhorn/v1.1.1/templates/serviceaccount.yaml
- charts/longhorn/v1.1.1/templates/storageclass.yaml
- charts/longhorn/v1.1.1/templates/tls-secrets.yaml
- charts/longhorn/v1.1.1/templates/uninstall-job.yaml
- charts/longhorn/v1.1.1/values.yaml
> Longhorn v1.1.2 release 

- index.yaml
Addresses https://github.com/rancher/charts/pull/1664#issuecomment-997120915
Related Issue: https://github.com/rancher/rancher/issues/35100
> Bring index.yaml back up-to-date
