- charts/prometheus/v6.2.1/questions.yml
fixed: using .service.type instead of .server.type for grafana and alertmanager type in questions.yml
> fixed service.type (grafana, alertmanager)

- charts/fluentd-aggregator/latest/README.md
- charts/fluentd-aggregator/latest/templates/statefulset.yaml
- charts/fluentd-aggregator/v0.1.0/.helmignore
- charts/fluentd-aggregator/v0.1.0/Chart.yaml
- charts/fluentd-aggregator/v0.1.0/README.md
- charts/fluentd-aggregator/v0.1.0/app-readme.md
- charts/fluentd-aggregator/v0.1.0/questions.yml
- charts/fluentd-aggregator/v0.1.0/templates/NOTES.txt
- charts/fluentd-aggregator/v0.1.0/templates/_helpers.tpl
- charts/fluentd-aggregator/v0.1.0/templates/configmap.yaml
- charts/fluentd-aggregator/v0.1.0/templates/ingress.yaml
- charts/fluentd-aggregator/v0.1.0/templates/secert.yaml
- charts/fluentd-aggregator/v0.1.0/templates/service-headless.yaml
- charts/fluentd-aggregator/v0.1.0/templates/service.yaml
- charts/fluentd-aggregator/v0.1.0/templates/statefulset.yaml
- charts/fluentd-aggregator/v0.1.0/values.yaml
This will allow us to configure additional annotations for statefulset
```
--set annotations."prometheus\.io/scrape"=true
--set annotations."prometheus\.io/port"=24231
--set annotations."prometheus\.io/path"=/metrics
```
> Add missing annotations for statefulset implementation

- proposed/storageos-operator/Chart.yaml
- proposed/storageos-operator/LICENSE
- proposed/storageos-operator/README.md
- proposed/storageos-operator/app-readme.md
- proposed/storageos-operator/ci/std-values.yaml
- proposed/storageos-operator/questions.yml
- proposed/storageos-operator/templates/NOTES.txt
- proposed/storageos-operator/templates/_helpers.tpl
- proposed/storageos-operator/templates/cleanup.yaml
- proposed/storageos-operator/templates/job_crd.yaml
- proposed/storageos-operator/templates/operator.yaml
- proposed/storageos-operator/templates/psp.yaml
- proposed/storageos-operator/templates/rbac.yaml
- proposed/storageos-operator/templates/secrets.yaml
- proposed/storageos-operator/templates/service-account.yaml
- proposed/storageos-operator/templates/storageoscluster_cr.yaml
- proposed/storageos-operator/templates/storageoscluster_crd.yaml
- proposed/storageos-operator/templates/storageosupgrade_crd.yaml
- proposed/storageos-operator/values.yaml
This PR adds the StorageOS chart and catalog integration.  A default deployment installs the StorageOS Operator and then a StorageOS cluster, allowing use of StorageOS for provisioning PVs.
StorageOS has been available on Rancher for some time but not integrated into the Rancher catalog.  Existing docs at: https://docs.storageos.com/docs/platforms/rancher/, which we'll update for the catalog.
> Add StorageOS chart

- proposed/storageos-operator/Chart.yaml
- proposed/storageos-operator/README.md
- proposed/storageos-operator/questions.yml
- proposed/storageos-operator/templates/cleanup.yaml
- proposed/storageos-operator/templates/rbac.yaml
- proposed/storageos-operator/templates/storageoscluster_cr.yaml
- proposed/storageos-operator/templates/storageoscluster_crd.yaml
- proposed/storageos-operator/values.yaml
We released an new version of the operator and base image yesterday.  The operator supports a new field, `csi.deploymentStrategy` which determines whether the CSI helpers are deployed by the Operator as StafefulSets (previous) or Deployments (new default).  The cleanup jobs have been amended to support both and ignore whichever wasn't created.
> Bump to storageos-operator 1.2.0 and node 1.2.1

- charts/openebs/latest/README.md
- charts/openebs/latest/templates/cm-node-disk-manager.yaml
- charts/openebs/latest/templates/daemonset-ndm.yaml
- charts/openebs/latest/templates/deployment-admission-server.yaml
- charts/openebs/latest/templates/deployment-local-provisioner.yaml
- charts/openebs/latest/templates/deployment-maya-apiserver.yaml
- charts/openebs/latest/templates/deployment-maya-provisioner.yaml
- charts/openebs/latest/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/latest/templates/validationwebhook.yaml
- Updated chart version
- Update pod labels for deployments
`pre-install` hook: Executes after templates are rendered,
but before any resources are created in Kubernetes.
This hook has been added to the secret , will only be generated
on chart install, to prevent overriding the certs anytime we upgrade
the chart’s released instance.
Thus `pre-install hook` prevents the secret creation if someone uses
the older version of charts and upgraded to new version.
Signed-off-by: prateekpandey14 <prateek.pandey@openebs.io>
> [openebs]: remove pre-install hook from secret and pod labels

- .drone.yml
Update the Drone lint-chart image to `v2.0.2-rancher2`, it adds skipping the `helm dep` check since we already add the sub-charts directly in our git repo, and the [CI]((https://drone-pr.rancher.io/rancher/charts/194/1/2)) will fail if we use uncompressed sub-charts.
> Update drone lint-chart image

- charts/cert-manager/v0.9.1/questions.yml
- charts/chartmuseum/v2.3.1/questions.yml
- charts/traefik/v1.7/questions.yml
**Problem**
Fix traefik typo and update chartmuseum default pv setting
**Related Issue:**
https://github.com/rancher/rancher/issues/23070#event-2660039893
https://github.com/rancher/rancher/issues/23072#event-2660051332
> Fix traefik typo and update chartmuseum default pv setting

- charts/cert-manager/v0.9.1/questions.yml
update cert-manager mini rancher version to `2.3.0-rc1` so QA would be able to test it.
> update cert-manager mini rancher version

- charts/cert-manager/v0.9.1/charts/webhook/templates/deployment.yaml
address `to error converting YAML to JSON: yaml: line 35: could not find expected ':'` as v0.5.2 cert-manger will set string `[]`.
> Add empty array check of webhook extraArg

- charts/kafka/v0.8.0/charts/cp-kafka/templates/statefulset.yaml
Enable metric env for enpterise image only
**Related Issue:**
https://github.com/rancher/rancher/issues/23460
> Enable metric env for enpterise image only

- charts/drone/v2.0.7/questions.yml
Fixing a small typo in the questions template. doamin -> domain.
> typo: doamin -> domain

- charts/neuvector/v1.2.3/Chart.yaml
- charts/redskyops/v0.1.1/questions.yml
- charts/redskyops/v0.1.2/questions.yml
- charts/traefik/v1.7/questions.yml
**Problem:**
Add missing partner label to `redskyops` and `traefik`, add neuvector logo using local path since the current URL is not showable.
> Add partner labels and fix neuvector logo

- README.md
The current link leads to a 404 page, I added the new link.
> Fixed link to helm docs

- charts/instana-agent/v1.0.19/.helmignore
- charts/instana-agent/v1.0.19/Chart.yaml
- charts/instana-agent/v1.0.19/OWNERS
- charts/instana-agent/v1.0.19/README.md
- charts/instana-agent/v1.0.19/app-readme.md
- charts/instana-agent/v1.0.19/questions.yml
- charts/instana-agent/v1.0.19/templates/NOTES.txt
- charts/instana-agent/v1.0.19/templates/_helpers.tpl
- charts/instana-agent/v1.0.19/templates/agentsecret.yaml
- charts/instana-agent/v1.0.19/templates/clusterrole.yaml
- charts/instana-agent/v1.0.19/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.19/templates/configmap.yaml
- charts/instana-agent/v1.0.19/templates/daemonset.yaml
- charts/instana-agent/v1.0.19/templates/downloadsecret.yaml
- charts/instana-agent/v1.0.19/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.19/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.19/values.yaml
This changeset includes:
- Mount `/var/lib/containers/storage` in the `DaemonSet` for CRI-O support
- Update the `instana/agent` image tag to the latest available `1.0.42` that's on DockerHub as of Dec 16 2019 (https://hub.docker.com/r/instana/agent/tags)
> Chart version 1.0.19

- charts/instana-agent/v1.0.22/.helmignore
- charts/instana-agent/v1.0.22/Chart.yaml
- charts/instana-agent/v1.0.22/OWNERS
- charts/instana-agent/v1.0.22/README.md
- charts/instana-agent/v1.0.22/app-readme.md
- charts/instana-agent/v1.0.22/questions.yml
- charts/instana-agent/v1.0.22/templates/NOTES.txt
- charts/instana-agent/v1.0.22/templates/_helpers.tpl
- charts/instana-agent/v1.0.22/templates/agentsecret.yaml
- charts/instana-agent/v1.0.22/templates/clusterrole.yaml
- charts/instana-agent/v1.0.22/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.22/templates/configmap.yaml
- charts/instana-agent/v1.0.22/templates/daemonset.yaml
- charts/instana-agent/v1.0.22/templates/downloadsecret.yaml
- charts/instana-agent/v1.0.22/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.22/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.22/values.yaml
Changes included in this PR:
- Allow users to specify any environment variable for the agent. This is to avoid having to create a new helm value whenever we need to set an environment variable in the agent, which is hard to maintain, not to mention confusing for our users.
- Increase liveness probe timeouts as we have had quite a few instances of overloaded agents getting killed on start up because the liveness probe is not generous enough. Therefore do the following for both the `instana-agent` and `leader-elector` containers:
- Increase initial delay to 5 minutes
- Increase timeout for each probe to 3 seconds
- Increase period to once every 10 seconds (the default)
> Chart version 1.0.22

- charts/instana-agent/v1.0.24/.helmignore
- charts/instana-agent/v1.0.24/Chart.yaml
- charts/instana-agent/v1.0.24/OWNERS
- charts/instana-agent/v1.0.24/README.md
- charts/instana-agent/v1.0.24/app-readme.md
- charts/instana-agent/v1.0.24/questions.yml
- charts/instana-agent/v1.0.24/templates/NOTES.txt
- charts/instana-agent/v1.0.24/templates/_helpers.tpl
- charts/instana-agent/v1.0.24/templates/agentsecret.yaml
- charts/instana-agent/v1.0.24/templates/clusterrole.yaml
- charts/instana-agent/v1.0.24/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.24/templates/configmap.yaml
- charts/instana-agent/v1.0.24/templates/daemonset.yaml
- charts/instana-agent/v1.0.24/templates/downloadsecret.yaml
- charts/instana-agent/v1.0.24/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.24/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.24/values.yaml
Changes included:
- Updated README to include install and uninstall instructions for both Helm 2 and Helm 3
- Please note that this chart is still 100% compatible with Helm 2 and can be deployed with Helm 2 indefinitely.
> Chart version 1.0.24

- charts/instana-agent/v1.0.25/.helmignore
- charts/instana-agent/v1.0.25/Chart.yaml
- charts/instana-agent/v1.0.25/OWNERS
- charts/instana-agent/v1.0.25/README.md
- charts/instana-agent/v1.0.25/app-readme.md
- charts/instana-agent/v1.0.25/questions.yml
- charts/instana-agent/v1.0.25/templates/NOTES.txt
- charts/instana-agent/v1.0.25/templates/_helpers.tpl
- charts/instana-agent/v1.0.25/templates/agentsecret.yaml
- charts/instana-agent/v1.0.25/templates/clusterrole.yaml
- charts/instana-agent/v1.0.25/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.25/templates/configmap.yaml
- charts/instana-agent/v1.0.25/templates/daemonset.yaml
- charts/instana-agent/v1.0.25/templates/downloadsecret.yaml
- charts/instana-agent/v1.0.25/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.25/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.25/values.yaml
This improves the liveness checks for the instana agent Kubernetes monitoring to ensure if the leader agent is not correctly monitoring Kubernetes, then leadership is relinquished.
> [instana/agent:1.0.25] Improved liveness checks

- charts/longhorn/v0.6.2/questions.yml
Keep it for the upgrade purpose from v0.5.0.
Signed-off-by: Sheng Yang <sheng.yang@rancher.com>
> longhorn: Allow up to Rancher v2.3.5 for Longhorn v0.6.2

- charts/instana-agent/v1.0.28/.helmignore
- charts/instana-agent/v1.0.28/Chart.yaml
- charts/instana-agent/v1.0.28/OWNERS
- charts/instana-agent/v1.0.28/README.md
- charts/instana-agent/v1.0.28/app-readme.md
- charts/instana-agent/v1.0.28/questions.yml
- charts/instana-agent/v1.0.28/templates/NOTES.txt
- charts/instana-agent/v1.0.28/templates/_helpers.tpl
- charts/instana-agent/v1.0.28/templates/agentsecret.yaml
- charts/instana-agent/v1.0.28/templates/clusterrole.yaml
- charts/instana-agent/v1.0.28/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.28/templates/configmap.yaml
- charts/instana-agent/v1.0.28/templates/daemonset.yaml
- charts/instana-agent/v1.0.28/templates/namespace.yaml
- charts/instana-agent/v1.0.28/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.28/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.28/values.yaml
- Add `cronjobs` ClusterRole permission
- Update default agent endpointHost value to `ingress-red-saas.instana.io` (US & ROW) and include `ingress-blue-saas.instana.io` (Europe) in README and description of field in `questions.yml` as an option
> Chart version 1.0.28

- charts/instana-agent/v1.0.29/.helmignore
- charts/instana-agent/v1.0.29/Chart.yaml
- charts/instana-agent/v1.0.29/OWNERS
- charts/instana-agent/v1.0.29/README.md
- charts/instana-agent/v1.0.29/app-readme.md
- charts/instana-agent/v1.0.29/questions.yml
- charts/instana-agent/v1.0.29/templates/NOTES.txt
- charts/instana-agent/v1.0.29/templates/_helpers.tpl
- charts/instana-agent/v1.0.29/templates/agentsecret.yaml
- charts/instana-agent/v1.0.29/templates/clusterrole.yaml
- charts/instana-agent/v1.0.29/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.29/templates/configmap.yaml
- charts/instana-agent/v1.0.29/templates/daemonset.yaml
- charts/instana-agent/v1.0.29/templates/namespace.yaml
- charts/instana-agent/v1.0.29/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.29/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.29/values.yaml
Expose new configuration options:
- `leaderElector.image.name`
- `leaderElector.image.tag`
Changed the existing `agent.leaderElectorPort` configuration value to `leaderElector.port` to be consistent with the other leader elector configurations.
> Chart version 1.0.29

- charts/aws-event-sources/v0.1.0/questions.yml
**Problem:**
The aws-event-sources chart is a Helm 3 chart and its CRDs will not install correctly when using Helm 2.
**Solution:**
Move chart to the [rancher/helm3-charts](https://github.com/rancher/helm3-charts) repository.
**Related PR:** https://github.com/rancher/helm3-charts/pull/21
> Deprecate aws-event-sources chart v0.1.0

- charts/artifactory-ha/v2.5.3/questions.yml
- charts/artifactory-jcr/v2.3.0/questions.yml
Without specifying a password, the charts were auto generating a password. This made upgrades and reinstalls fail as that generated a new password and the data saved on persistent volume was not readable.
Now we are giving the user to specify a password. So on upgrades and reinstalls they can specify the same password and upgrades and reinstalls will suceed.
Note: To reinstall without reusing the data, user needs to delete install, delete PVs, then reinstall. In this case, the data will be removed and the user can also specify a different password if desired.
> Added a 'required' option for user to specify PostgreSQL password. 

- scripts/generate-patch
Update patch for mac compatibility
Without this change the patch script will not work in macOS.
Throws an error similar to this:
```
sed: 1: "packages/rancher-gateke ...": extra characters at the end of p command                                                                         
make: *** [patch] Error 1 
```
> Update patch for mac compatibility

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/charts/README.md
- packages/rancher-istio/charts/configs/istio-base.yaml
- packages/rancher-istio/charts/samples/overlay-example.yaml
- packages/rancher-istio/charts/templates/_helpers.tpl
- packages/rancher-istio/charts/templates/admin-role.yaml
- packages/rancher-istio/charts/templates/base-config-map.yaml
- packages/rancher-istio/charts/templates/clusterrolebinding.yaml
- packages/rancher-istio/charts/templates/edit-role.yaml
- packages/rancher-istio/charts/templates/istio-install-job.yaml
- packages/rancher-istio/charts/templates/istio-uninstall-job.yaml
- packages/rancher-istio/charts/templates/overlay-config-map.yaml
- packages/rancher-istio/charts/templates/service-monitors.yaml
- packages/rancher-istio/charts/templates/serviceaccount.yaml
- packages/rancher-istio/charts/templates/view-role.yaml
- packages/rancher-istio/charts/values.yaml
Change namespace from istio-system to cattle-istio system
-- Left option to default to istio-system if being installed on own an not through rancher
Change istioctl-installer job to delete on success (to ensure namespace is clear after uninstall)
Add value to set for forceInstall to bypass version checks and analyze checks in installer script
Added back in addon components since those are still available until 1.7.x (and we are currently at 1.6.7)
> Istio Phase 2: Change namespace, add forceInstall flag

- scripts/generate-patch
This PR resolves two issues that are found when working with charts:
- On a failed sed command for removing the timestamp, the patch also
fails to regenerate the CRD package. Since removing the timestamps on the patch
before or after generating the CRD package makes no difference, we can just
move the `remove_timestamp_from_diff` command to the end of the for loop.
- The sed command would fail depending on what type of sed you were using.
The easiest fix is to provide a backup file extension name like `.bak` and just
delete the file after generating it to have it work with both types of sed.
Related comment for second issue: https://github.com/rancher/dev-charts/pull/38#discussion_r458442691
> Fix remove_timestamp_from_diff in generate-patch

- packages/rancher-istio/charts/templates/istio-install-job.yaml
- packages/rancher-istio/charts/values.yaml
Needed to create a an older version of istio with recent changes (name change, remove canary, manifest changes) for upgrade testing
> Remove canary and set version to 1.6.7 for upgrade testing

- scripts/generate-patch
- scripts/prepare
- scripts/prepare-subcharts
This commit adds the ability to add patches on subcharts in `rancher/charts` that meet the following constraints:
- Must be a remote chart (i.e. the repo url cannot point to a `file://<path>`)
- Must have a fixed version number (since we need a consistent base to apply the patch on)
The following changes have been made to the scripts to faciliate this feature:
**prepare**
Only run the patch after preparing the subchart
**prepare-subcharts:**
Inital checks:
1. We only prepare the subcharts if the chart has a `requirements.yaml`.
2. Extract the patches that would be applied to the requirements.yaml and only apply that
Note: in the future, we need to add support for dependencies outlined in the Chart.yaml directory, which is currently the recommended approach for Helm 3 charts that use …
> Allow patches on remote deps with fixed versions

- README.md
- scripts/clean
- scripts/generate-patch
- scripts/prepare
**Problem**
The ability to generate CRD charts is tied to the `package.yaml` file existing and the` url` key value being set. This does not support CRD generation when the chart has locally defined crds(usually found at the following path `<path>/<chart>/charts/crds`)
_Note: If the `package.yaml` doesn't exist, then no crd generation or patching occurs_ 
**Solution**
When a chart has a `package.yaml`  file and if no ` url` key value is present, the local chart's crds directory will be generated. This occurs by checking that the package.yaml file exists and only runs url specific commands if the url also exits. 
Updated clean command to only run if the charts-crd directory exists for charts that have a `package.yaml` file
Generate patch is also skipped for charts that have a `package.yaml` …
> Add generate CRD for charts that don't have a url in package.yaml

- scripts/clean
- scripts/clean-crds
- scripts/generate-patch
- scripts/prepare
- scripts/validate
This PR deprecates the provideGVR flag and updates the validate script to unblock CI issues for local charts that use the generateCRDChart flag.
Related to build failures in https://github.com/rancher/charts/pull/594
> Deprecate providesGVR flag and update validate script

- packages/backup-restore-operator/charts/Chart.yaml
- packages/backup-restore-operator/charts/crds/backup.yaml
- packages/backup-restore-operator/charts/crds/resourceset.yaml
- packages/backup-restore-operator/charts/crds/restore.yaml
- packages/backup-restore-operator/charts/templates/_helpers.tpl
- packages/backup-restore-operator/charts/templates/clusterrolebinding.yaml
- packages/backup-restore-operator/charts/templates/deployment.yaml
- packages/backup-restore-operator/charts/templates/pvc.yaml
- packages/backup-restore-operator/charts/templates/rancher-resourceset.yaml
- packages/backup-restore-operator/charts/templates/s3-secret.yaml
- packages/backup-restore-operator/charts/templates/serviceaccount.yaml
- packages/backup-restore-operator/charts/values.yaml
- packages/backup-restore-operator/package.yaml
This chart needs to create a CR when its installed. So as per offline discussion of making original charts similar in structure to upstream chart, this chart has all its CRDs in the /crds folder. And the CR it should create is in the templates folder.
Carrying over all relevant comments from https://github.com/rancher/charts/pull/589
This chart creates:
1. ServiceAccount bound to the cluster-admin role, which is used for launching the operator deployment. This operator needs CRUD permissions on all resources in the cluster. Hence only cluster-admin should be able to operate it. That's why it was decided in design meetings to assign it the cluster-admin role and have no other roles for it.
2. The CRDs in crds folder are generated using wrangler's CRD definition and openapi schema package. …
> Add chart for backup-restore-operator

- scripts/validate
This PR cleans up the validate script in order to resolve CI errors.
The core reason why the script became so complicated was that we would check whether Git was dirty when running validate. This was originally intended for either:
- Remote charts (with url in `package.yaml`): check if their `overlay/` or `package.yaml` or `*.patch` files were committed
- Local charts: check if all of their files were committed; since `prepare` performed a noop for these charts, there were no other issues.
However, with the recent changes that allowed local charts to also be `prepare`ed (via the `generateCRDChart` flag), the `prepare-crd` script would modify the local state of the chart to update the Chart.yaml and the contents of the `crd/` directory. While these were initially resolved by just running …
> Fix validate errors

- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/README.md
- packages/rancher-cis-benchmark/charts/crds/clusterscan.yaml
- packages/rancher-cis-benchmark/charts/crds/clusterscanbenchmark.yaml
- packages/rancher-cis-benchmark/charts/crds/clusterscanprofile.yaml
- packages/rancher-cis-benchmark/charts/crds/clusterscanreport.yaml
- packages/rancher-cis-benchmark/charts/templates/_helpers.tpl
- packages/rancher-cis-benchmark/charts/templates/benchmark-cis-1.5.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-eks-1.0.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-gke-1.0.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-rke-cis-1.5-hardened.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-rke-cis-1.5-permissive.yaml
- packages/rancher-cis-benchmark/charts/templates/cis-roles.yaml
- packages/rancher-cis-benchmark/charts/templates/configmap.yaml
- packages/rancher-cis-benchmark/charts/templates/deployment.yaml
- packages/rancher-cis-benchmark/charts/templates/rbac.yaml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-cis-1.5.yml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-rke-hardened.yml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-rke-permissive.yml
- packages/rancher-cis-benchmark/charts/templates/scanprofileeks.yml
- packages/rancher-cis-benchmark/charts/templates/scanprofilegke.yml
- packages/rancher-cis-benchmark/charts/templates/serviceaccount.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
- packages/rancher-cis-benchmark/package.yaml
Updated:
--------------
- NO separate CRD chart. Combine CRDs into rancher-cis-benchmark/crds chart itself.
- Add a package.yaml under rancher-cis-benchmark chart
- Added the linux nodeSelector and tolerations
---------------
Adding two charts for CIS v2 feature:
- rancher-cis-benchmark-crds - CRD chart
- rancher-cis-benchmark - chart deploying rancher/cis-operator
Commands to install the charts:
helm install clusterscan-operator ./rancher-cis-benchmark/charts/ --create-namespace=true -n cis-operator-system --
kubeconfig <kubeconfig>
Commands to uninstall the charts:
helm uninstall clusterscan-operator -n cis-operator-system --kubeconfig <kubeconfig>
> CIS v2 charts

- packages/backup-restore-operator/charts/Chart.yaml
- packages/backup-restore-operator/charts/templates/pvc.yaml
- packages/backup-restore-operator/charts/values.yaml
The field storageClassName uses "quote" template function. So the quotes around it lead to errors. This commit removes the quotes
https://github.com/rancher/backup-restore-operator/issues/27
> Remove quotes around pvc storageClassName

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/charts/configs/istio-base.yaml
- packages/rancher-istio/charts/requirements.yaml
- packages/rancher-istio/charts/values.yaml
- packages/rancher-kiali-server/package.yaml
- packages/rancher-kiali-server/rancher-kiali-server.patch
**Dependency**
https://github.com/rancher/image-mirror/pull/36
**Problem**
Istio 1.7.1 and Kiali 1.23.0 were released
Kiali was not hard coded to specific name
**Solution** 
Update images and chart patches / values for new version
New version of Kiali hard codes name to Kiali 
**Issue**
https://github.com/rancher/rancher/issues/28901
> Image updates for Istio 1.7.1 and Kiali 1.23.0

- packages/rancher-logging/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/rancher-logging.patch
PROBLEMS:
- airgap install fails
- k3s installs require a pvc
SOLUTION:
- added registry prefix to operator image
- override the config reloading images
- ensured the pvc toggle is passed to all loggings
> fixed airgap images

- scripts/produce-sha256
Related Issue: https://github.com/rancher/rancher/issues/29173
Dependent on merge:
> Allow new charts to generate sums

- packages/rancher-backup/charts/README.md
The README contains a table explaining configurable parameters. The alignment of all columns in this table was different. This commit left-aligns all columns
This is what it looks like in UI currently:
This is what it looks like with this commit:
> Left align all columns in Readme table

- packages/rancher-backup/charts/templates/_helpers.tpl
- packages/rancher-backup/charts/templates/deployment.yaml
This commit modifies the helper for creating PVC name to address this bug
https://github.com/rancher/backup-restore-operator/issues/39
The chart name was used as PVC name till now, because of which if you upgrade the chart to use a different Persistent Volume, it would use the same PVC since the chart name stays constant. Now PVC is named with a combination of release name and revision number so it changes each time on upgrade. The PVC will be recreated and the annotation in the deployment will launch a new pod to use the new PV
Also removed the nfs pv helper which is no longer used
> Add ability to create new PVC on upgrade

- packages/rancher-logging/overlay/templates/userroles.yaml
Removed edit from cluster members and allowed all users to view cluster level crds.
> fixed logging roles

- packages/rancher-monitoring/rancher-monitoring.patch
To allow users to have non-readonly access (since the default role is `Viewer` based on https://github.com/rancher/rancher/issues/29165#issuecomment-700255212), we need to enable the login page.
> Enable login form by default

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/charts/configs/istio-base.yaml
- packages/rancher-istio/charts/values.yaml
**Problem:**
Telemetry V2 was is not getting enabled. Current chart is still using Telemetry v1. 
Kiail version for the chart.yaml auto-install annotation is 1.22.x, not 1.23.x
**Solution:**
Change auto-install annotation to correct kiali version
Disable mixer telemetry and policy. Add configuration for tTelemetry v2. 
**Issue:** 
https://github.com/rancher/rancher/issues/29169
https://github.com/rancher/rancher/issues/28738
> Correct Kiali Version, Enable Telemetry V2

- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
Updating chart tags for cis-operator and security-scan images and setting app version to v0.2.0
https://github.com/rancher/cis-operator/issues/37
> Updating chart tags for cis-operator and security-scan images and set version to v0.2.0

- packages/rancher-backup/charts/Chart.yaml
- packages/rancher-backup/charts/templates/rancher-resourceset.yaml
This PR reverts the changes made to rancher's default resource set in [this PR](https://github.com/rancher/charts/pull/678/files), except for the one to exclude helm secrets. 
Also adds in the link to rancher-backup chart icon (the icon file is merged in dev-v2.5 branch)
https://github.com/rancher/backup-restore-operator/issues/44
https://github.com/rancher/backup-restore-operator/issues/42
https://github.com/rancher/backup-restore-operator/issues/30#issuecomment-700982880
> Remove rancher-operator, fleet and rancher-webhook charts from resource-set

- packages/rancher-backup/charts/Chart.yaml
- packages/rancher-backup/charts/values.yaml
This commit adds the new tag v1.0.0 for rancher-backup operator, and changes chart version to 1.0.000
> Update chart version and opertor tag for rancher-backup

- packages/rancher-istio/charts/README.md
**Problem**
rancher-istio chart uses `catalog.cattle.io/requires-gvr: monitoring.coreos.com.prometheus/v1` to trigger the ui to request for rancher-monitoring installation. Since we cannot guarantee what installed `monitoring.coreos.com.prometheus/v1` we need an additional way to let the user know how to configure the chart
**Solution**
Update the readme to make the chart dependencies more obvious
**Issue**
https://github.com/rancher/rancher/issues/29295
> Update readme to show dependencies better

- packages/rancher-istio/charts/README.md
With the changes here https://github.com/rancher/charts/pull/752, having the additional monitoring config options in the readme is no longer needed.
> Removing additional monitoring config info

- packages/rancher-backup/charts/Chart.yaml
- packages/rancher-backup/charts/values.yaml
v1.0.2 includes the fix for https://github.com/rancher/backup-restore-operator/issues/49
> Update rancher-backup chart version to use v1.0.2 tag

- scripts/chart-templates/crd-base/README.md
Issue: https://github.com/rancher/rancher/issues/29219
We could fix link, but its prone to change again, and going between dev/main is tricky.
> [2.5.1] remove link from readme in crd charts

- packages/rancher-logging/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/overlay/templates/loggings/rke/logging-containers-rke.yaml
- packages/rancher-logging/overlay/templates/loggings/rke/logging-rke.yaml
- packages/rancher-logging/overlay/templates/loggings/rke2/daemonset.yaml
- packages/rancher-logging/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/overlay/templates/loggings/rke2/logging-rke2-journald.yaml
- packages/rancher-logging/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/rancher-logging.patch
Ensure logging pods only run on Linux nodes by adding tolerations and
node selectors for fluentbit and fluentd. The tolerations have
"NoSchedule" for Windows nodes, and the node selectors look for nodes
with a Linux-based OS.
Solves issue: [28720](https://github.com/rancher/rancher/issues/28720)
Please note: this is a re-opened version of PR #775 due to force-push error
> Ensure logging pods only run on Linux nodes

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/charts/app-readme.md
- packages/rancher-istio/charts/requirements.yaml
- packages/rancher-istio/charts/values.yaml
- packages/rancher-istio/scripts/version_update.go
- packages/rancher-kiali-server/package.yaml
- packages/rancher-kiali-server/rancher-kiali-server.patch
**Problem**
Kiali released version 1.24.0
Istio released version 1.7.3 (this is a security release)
Older versions of installer use verify-install which does not work as expected in all scenarios
**Solution**
Update versions for kiali and istio to match the latest releases 
With the istio version update, the new installer without verify-install is used
Also added script to make updating the versions a lot easier. On occasion I would miss a value, the script ensures all values are getting updated as expected. 
**Issues**
rancher/rancher#29383
rancher/rancher#29249
rancher/rancher#29408
**Dependencies**
https://github.com/rancher/istio-installer/pull/12
> Update Istio and Kiali Versions

- packages/rancher-pushprox/charts/templates/pushprox-clients-rbac.yaml
Preventing PushProx client pods from using secret volumes prevents the clients from being deployed in a hardened cluster since the Pod requires the ability to mount the service account token as a secret to use the PSP in the first place.
Related Issues: https://github.com/rancher/rancher/issues/29059, https://github.com/rancher/rancher/issues/28536, https://github.com/rancher/rancher/issues/18044
> Allow any PushProx client to use secret volumes

- packages/rancher-logging/rancher-logging.patch
Fix fluentbit debug image addition from recent image-mirror change. We
need to add the image to values.yaml even though it is not currently in
use.
Issue: [#28657](https://github.com/rancher/rancher/issues/28657)
> [2.5] Fix fluentbit debug image addition

- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/crds/scheduledscan.yaml
- packages/rancher-cis-benchmark/charts/templates/cis-roles.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
1) Updating the chart to point to new cis-operator tag that pulls the scheduled Scan functionality
- https://github.com/rancher/cis-operator/issues/27
2) Also removing the aggregator label from cis ClusterRoles since the aggregation does not apply to cluster scoped CIS CRDs
3) Also removing the namespace from ClusterRoles since namespace is not required for ClusterRoles that applies cluster wide.
- https://github.com/rancher/cis-operator/issues/41
> Updating cis-operator tag and updating cis ClusterRoles to drop label and ns

- packages/rancher-monitoring/rancher-monitoring.patch
The initChown container needs to run as root user so that runAsNonRoot
has to be disabled to respect root user setting
> Add runAsNonRoot to false to override init container

- packages/rancher-monitoring/overlay/app-README.md
~I'm blocking the merge of this to `rancher/charts` on https://github.com/rancher/charts/pull/814. While they are unrelated issues, due to a constraint on our charts scripts atm we need to push a dummy commit to `rancher-monitoring` to absorb `rancher-pushprox` changes anyways (since the sha256sum needs to change), so this would be the easiest way to handle that.~
edit: Never mind, we're making a change anyways to the rancher-monitoring chart to upgrade the pushprox version.
Related Issue: https://github.com/rancher/rancher/issues/29547
> Remove helm command from app-README.md

- packages/rancher-monitoring/rancher-monitoring.patch
- packages/rancher-pushprox/charts/Chart.yaml
- packages/rancher-pushprox/charts/templates/pushprox-clients.yaml
The issue in https://github.com/kubernetes/kubernetes/issues/83125 was encountered when trying to use /opt/rke/etc/kubernetes/ssl as the hostPath. Removing this resolves it.
Related Issue: https://github.com/rancher/rancher/issues/29815
> Remove hostPath type from PushProx client

- charts/instana-agent/v1.0.33/.helmignore
- charts/instana-agent/v1.0.33/Chart.yaml
- charts/instana-agent/v1.0.33/OWNERS
- charts/instana-agent/v1.0.33/README.md
- charts/instana-agent/v1.0.33/app-readme.md
- charts/instana-agent/v1.0.33/questions.yml
- charts/instana-agent/v1.0.33/templates/NOTES.txt
- charts/instana-agent/v1.0.33/templates/_helpers.tpl
- charts/instana-agent/v1.0.33/templates/agentsecret.yaml
- charts/instana-agent/v1.0.33/templates/clusterrole.yaml
- charts/instana-agent/v1.0.33/templates/clusterrolebinding.yaml
- charts/instana-agent/v1.0.33/templates/configmap.yaml
- charts/instana-agent/v1.0.33/templates/daemonset.yaml
- charts/instana-agent/v1.0.33/templates/namespace.yaml
- charts/instana-agent/v1.0.33/templates/podsecuritypolicy.yaml
- charts/instana-agent/v1.0.33/templates/serviceaccount.yaml
- charts/instana-agent/v1.0.33/values.yaml
Use `dnsPolicy: ClusterFirstWithHostNet` as this should be the default for pods with `hostNetwork: true` according to https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
https://github.com/helm/charts/issues/23910
> Chart version 1.0.33

- scripts/generate-charts
This reverts commit f3d83c68fccd7ee33bd3edd1fac35743583ee7cc.
The original PR introduces a bug in the push-to-assets-branch process that makes the generated `charts/` directory not show the Chart version change + overlaid files.
Original PR: https://github.com/rancher/charts/pull/842
Related Issue: https://github.com/rancher/rancher/issues/29064
> Revert "Add cleanup steps to make charts"

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-kiali-server/package.yaml
- packages/rancher-kiali-server/rancher-kiali-server.patch
Signed-off-by: Bastian Hofmann <bashofmann@gmail.com>
Opening new to resolve merge conflicts so we can merge 
**Original PR**
https://github.com/rancher/charts/pull/826
**Problem**
The server.web_root has a helper method that is defaulting to /kiali so on refresh, the window.web_root is expected to have /kiali appended, but it doesn't so an error page occurs
**Solution**
Changed the window webroot to have `/kiali` appended on, so that it matched the default helper web_root. 
**Issue**
rancher/rancher#29898
> Adapt overridden kiali webroot to correct kiali service name

- packages/rancher-logging/package.yaml
- packages/rancher-logging/rancher-logging.patch
Update logging chart with upstream version 3.7.3 and disable
serviceMonitor installation.
EDIT: added second commit to support syslog (https://github.com/rancher/rancher/issues/29892)
Completes issue: [#29642](https://github.com/rancher/rancher/issues/29642)
Prerequisite for completing issue: [#28720](https://github.com/rancher/rancher/issues/28720)
> Update logging chart with upstream version 3.7.3

- README.md
Add updating chart with upstream workflow. This includes a
troubleshooting section.
EDIT: you can see what the README looks like rendered [here](https://github.com/nickgerace/rancher-charts/blob/dev-v2.5-source-docs/README.md).
> Add updating chart with upstream workflow

- packages/rancher-gatekeeper/package.yaml
- packages/rancher-gatekeeper/rancher-gatekeeper.patch
Rebase gatekeeper to v3.2.1 and add `ui-component` annotation
Related Issue: https://github.com/rancher/rancher/issues/30018
PR dependency: https://github.com/rancher/image-mirror/pull/53
> Rebase gatekeeper to v3.2.1 + add ui-component annotation

- packages/rancher-logging/package.yaml
- packages/rancher-logging/rancher-logging.patch
Update logging chart with upstream version 3.8.0. This adds syslog
output support.
Relevant issue: https://github.com/rancher/rancher/issues/29892
Dependent PR: https://github.com/rancher/image-mirror/pull/54
> Update logging chart with upstream version 3.8.0

- packages/rancher-gatekeeper/package.yaml
If gatekeeper is already installed on a rancher-2.4 cluster, then after upgrading to 2.5 if user wants to update gatekeeper app to its latest GA chart, there is no upgrade path. 
User has to uninstall the 2.4 gatekeeper via ember UI and then re-install the new rancher-gatekeeper app via Cluster-Explorer
Even if the previous gatekeeper is uninstalled, helm2 does not delete the crds. These crds are installed by another helm release and so while installing the 2.5 rancher-gatekeeper the crd installation errors out.
The CRD's have not changed between the 2 gatekeeper releases, hence we can just transfer the ownership to the 2.5 helm release by adding flag assumeOwnershipOfCRD to the chart
https://github.com/rancher/rancher/issues/29188
After applying this fix following tests have been …
> Add generateCRDChart.assumeOwnershipOfCRDs for rancher-gatekeeper

- packages/rancher-backup/charts/Chart.yaml
- packages/rancher-backup/charts/templates/s3-secret.yaml
- packages/rancher-backup/charts/values.yaml
The s3 configuration details are passed to the backup-restore-operator through a Secret, setting the stringData field. InsecureSkipVerify cannot have boolean value as a part of stringData. So the operator will now parse this field as a string and then convert it to boolean while using it. This commit quotes the value to avoid errors related to stringData given in this bug
https://github.com/rancher/backup-restore-operator/issues/56
This only applies when installing/upgrading the chart.
https://github.com/rancher/charts/issues/864
> [2.5.4] Quote insecure skip verify to avoid parse errors

- packages/rancher-istio/charts/configs/istio-base.yaml
- packages/rancher-istio/charts/values.yaml
**Problem**
Istio CNI can be enabled via the values.yaml and ui, but the default values for it to work out of the box are not set
**Solution**
Add values needed for CNI to work without additional configuration
Note: CNI is still disabled by defautl
**Issue**
https://github.com/rancher/rancher/issues/27377
**How I tested it** 
1. Created a new cluster with podSecurityPolicy set to restricted
2. Follow step 1 of docs to allow istio to install properly https://rancher.com/docs/rancher/v2.x/en/istio/v2.3.x-v2.4.x/setup/enable-istio-in-cluster/enable-istio-with-psp/#1-configure-the-system-project-policy-to-allow-istio-install 
3. Installed istio, leaving cni disabled (this also requires installing rancher-monitoring, unless you disable kiali)
4. Installed the book info app
```
kubectl label …
```
> Add cni defaults

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/charts/README.md
- packages/rancher-istio/charts/app-readme.md
- packages/rancher-istio/charts/requirements.yaml
- packages/rancher-istio/charts/values.yaml
- packages/rancher-tracing/charts/.helmignore
- packages/rancher-tracing/charts/Chart.yaml
- packages/rancher-tracing/charts/README.md
- packages/rancher-tracing/charts/templates/_affinity.tpl
- packages/rancher-tracing/charts/templates/_helpers.tpl
- packages/rancher-tracing/charts/templates/deployment.yaml
- packages/rancher-tracing/charts/templates/pvc.yaml
- packages/rancher-tracing/charts/templates/service.yaml
- packages/rancher-tracing/charts/values.yaml
**Problem**
Istio 1.7.x needs Jaeger support
**Solution**
No upstream helm chart of jaeger all-in-one exists, so added jaeger all in one templates to istio chart
This is not a solution that is for heavy production needs and is the same Jaeger installation type that was provided as part Istio V1. This is documented in the app-readme. 
**Issues**
https://github.com/rancher/rancher/issues/29903
**Dependent PRs**
https://github.com/rancher/image-mirror/pull/52
Related Issues:
https://github.com/rancher/dashboard/issues/1928
https://github.com/rancher/dashboard/issues/1863
Additional Information: 
Here are the additional Jaeger upstream charts https://github.com/jaegertracing/helm-charts/tree/master/charts
Using Jaeger with Istio: https://istio.io/latest/docs/tasks/observability/distributed-tra …
> Add in jaeger tracing all-in-one

- packages/rancher-cis-benchmark/charts/crds/clusterscan.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-cis-1.6.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-rke-cis-1.6-hardened.yaml
- packages/rancher-cis-benchmark/charts/templates/benchmark-rke-cis-1.6-permissive.yaml
- packages/rancher-cis-benchmark/charts/templates/configmap.yaml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-cis-1.6.yaml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-rke-1.6-hardened.yaml
- packages/rancher-cis-benchmark/charts/templates/scanprofile-rke-1.6-permissive.yaml
This PR adds the CRs for CIS 1.6 benchmark and profiles. https://github.com/rancher/rancher/issues/29649
It also adds following changes to the clusterScan CRD:
1. AdditionalPrinterColumn "Warn" to show number of tests with "Warn" output. https://github.com/rancher/security-scan/issues/32
2. Field called `scoreWarning`, with which users can decide whether a scan should pass or fail if there are tests with "warn" output. https://github.com/rancher/cis-operator/issues/54
> CIS report changes and add CIS 1.6

- packages/rancher-cis-benchmark/charts/templates/alertingrule.yaml
- packages/rancher-cis-benchmark/charts/templates/deployment.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
- Add new cis-operator image for delivering scheduling - already has been added upstream by other CIS changes.
- Add alertingrule and podmonitor
- Expose containrPort to export metrics from cis-operator
- Update ClusterScan CRD - already done by another CIS charts PR
https://github.com/rancher/cis-operator/issues/27
https://github.com/rancher/cis-operator/issues/28
https://github.com/rancher/cis-operator/issues/6
> CIS v2 charts PR for Scheduling and Alerting

- packages/rancher-logging/package.yaml
- packages/rancher-logging/rancher-logging.patch
Update logging chart to 3.8.2 for syslog fix. This fixes the syslog
output inclusion into the outputs CRD.
Relevant issue: https://github.com/rancher/rancher/issues/29892
Dependent PR: https://github.com/rancher/image-mirror/pull/57
> Update logging chart to 3.8.2 for syslog fix

- packages/rancher-backup/charts/Chart.yaml
https://github.com/rancher/rancher/issues/30450
> Add annotation to hide backup chart from windows cluster

- packages/rancher-monitoring/rancher-monitoring.patch
The first commit is a quick fix to the patch file due to a change probably introduced in https://github.com/rancher/charts/pull/844/commits/004adafa21ae7baf7a9bbf2f617bad3aa21ce3a4.
It was never caught before probably because we never ran make prepare + make patch after making the changes.
The second commit adds the annotation.
Related Issue: https://github.com/rancher/rancher/issues/30450
> Add catalog.cattle.io/os=linux to monitoring and minor fix to patch

- packages/longhorn/longhorn.patch
- packages/longhorn/package.yaml
Needs a package bump because there is no new chart yet in this release: https://github.com/rancher/charts/blob/main-source/packages/longhorn/package.yaml#L5
Issue: rancher/rancher#30450
> Adds linux annotation to longhorn chart

- packages/rancher-cis-benchmark/charts/templates/configmap.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
Carry information about multiple rke profiles according to k8s major versions supported.
https://github.com/rancher/cis-operator/issues/84
> Update default profiles configmap to carry k8s version info for rke profiles

- packages/rancher-cis-benchmark/charts/values.yaml
Removing the rc tags from cis-operator and security-scan images for 2.5.4 release
> Updating CIS chart image tags to use non-rc tags

- packages/rancher-logging/overlay/templates/loggings/rke/daemonset.yaml
Fix fluent-bit directory overwrite by using subPath to mount the config
file. Fix tail-db directory existence by using DirectoryOrCreate volume
type. These changes affect RKE logging.
Relevant issue: https://github.com/rancher/rancher/issues/30595
> [2.5.6] Fix fluent-bit and tail-db directories

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/charts/values.yaml
**Problem**
Update to Istio 1.7.6 to support small issue fixes
**Solution**
Add support for 1.7.6
No changes were needed for the Operator Overlay file. 
sidecarInjectorWebhook values were not being used in any templates so they were removed to avoid confusion. 
**Issue**
https://github.com/rancher/rancher/issues/29812
**Dependent PR**
https://github.com/rancher/istio-installer/pull/14
https://github.com/rancher/image-mirror/pull/61
> Change Istio version to 1.7.6

- packages/rancher-logging/generated-changes/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/logging-rke.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-journald.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Expose fluentbit mountPath for Docker root directory. Move
fluentbit_tolerations to the same location as mountPath in values.yaml.
Relevant issue: rancher/rancher#30329
Original PR before charts changeover: https://github.com/rancher/charts/pull/926
> [Logging v2] Expose fluentbit mountPath for Docker root dir

- packages/rancher-istio/charts/README.md
- packages/rancher-istio/charts/app-readme.md
- packages/rancher-istio/charts/values.yaml
- packages/rancher-istio/package.yaml
**Issue**
Kiali was showing error in dashboard indicating that it was unable to get Jaeger traces
**Solution**
Update Jaeger URL and Grafana URL to the correct urls to ensure Kiali has access to them
**Issue**
https://github.com/rancher/rancher/issues/30752
> Add context path for jaeger, added grafana urls

- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/package.yaml
**Issue**
V1 version of Istio chart had a minimum cpu and memory requirement for cluster - V2 needs the same thing
**Solution**
Chart annotations will be added for rancher to use to check space and added ui warning
**Issue**
https://github.com/rancher/rancher/issues/30144
> Adding cpu, memory chart annotations

- packages/rancher-logging/generated-changes/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/logging-rke.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-journald.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Relevant issue: https://github.com/rancher/rancher/issues/30329
**Summary:** exposing `mountPath` for every `additionalLoggingSource` is unnecessary since the _provider_ determines the logging source. However the `root` logging CR and the `rke` logging CR specifically use `/var/docker/containers`. Thus, in order to solve the original issue, the chart's `mountPath` has be refocused to addressing the `dockerRootDirectory` only.
> Consolidate mountPath to dockerRootDir for logging

- packages/rancher-backup/package.yaml
- packages/rancher-istio/charts/Chart.yaml
- packages/rancher-istio/charts/README.md
- packages/rancher-istio/charts/values.yaml
- packages/rancher-istio/package.yaml
**Problem**
1. Istio release new Istio 1.8.3 version
2. Uninstall error occurs when chart dependencies are removed prior to rancher-istio gets removed
**Solution**
1.Add a chart to support Istio 1.8.3
2.Add documentation about the uninstall process to chart readme. 
**Issue**
https://github.com/rancher/rancher/issues/31187
https://github.com/rancher/rancher/issues/31046
**Dependent PRs**
https://github.com/rancher/image-mirror/pull/73
https://github.com/rancher/istio-installer/pull/17
**Additional Notes**
Kiali and Jaeger version did not change from 1.8.1 to 1.8.3
> Adding Istio 1.8.3

- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/daemonset.yaml
- packages/rancher-logging/package.yaml
Without this patch, the rancher-logging chart fails to install when RKE2
is included:
```
$ helm install rancher-logging rancher/rancher-logging --set additionalLoggingSources.rke2.enabled=true
Error: YAML parse error on rancher-logging/templates/loggings/rke2/daemonset.yaml: error converting YAML to JSON: yaml: line 25: did not find expected key
```
This is because the indentation being generated was invalid, which
itself was caused by the invalid use of `tolerations` and `nodeSelector`
under the `containers` object, when these are only Pod attributes. This
change fixes the indendation so that the end result is a valid pod spec
and the chart installs correctly.
https://github.com/rancher/rancher/issues/31372
> Fix RKE2 aggregator DaemonSet for rancher-logging

- packages/rancher-monitoring/generated-changes/patch/Chart.yaml.patch
- packages/rancher-monitoring/package.yaml
This commit addresses a regression introduced in the charts script rewrite as seen in charts-diff [here](https://github.com/aiyengar2/charts-diff/blob/a6535725f6295921bd2c7bc830dad9f28b9a291a/diff/rancher-monitoring.diff#L17).
The annotation needs to be added back in till we get Windows Monitoring out, which is now scheduled for 2.5.7.
Related Issue: https://github.com/rancher/rancher/issues/31421
> Add back in linux-only toleration

- README.md
Old link: https://helm.sh/docs/topics/chart_template_guide/
New link: https://helm.sh/docs/chart_template_guide/
> Fix broken link to helm chart dev guide

- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/clusterrole.yaml
- packages/rancher-monitoring/generated-changes/patch/templates/_helpers.tpl.patch
- packages/rancher-monitoring/package.yaml
This commit adds the minimal permissions required for users to be able to access the various UIs for accessing Prometheus, Grafana, and Alertmanager via a kubectl proxy and access the Monitoring Pane.
Related Issue: https://github.com/rancher/rancher/issues/31411
> Create default ClusterRole for accessing Monitoring UIs

- packages/rancher-monitoring/generated-changes/dependencies/windowsExporter/dependency.yaml
- packages/rancher-monitoring/generated-changes/patch/Chart.yaml.patch
- packages/rancher-monitoring/generated-changes/patch/values.yaml.patch
- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/.helmignore
- packages/rancher-windows-exporter/charts/Chart.yaml
- packages/rancher-windows-exporter/charts/README.md
- packages/rancher-windows-exporter/charts/scripts/copy-binary.ps1
- packages/rancher-windows-exporter/charts/scripts/proxy-entry.ps1
- packages/rancher-windows-exporter/charts/templates/_helpers.tpl
- packages/rancher-windows-exporter/charts/templates/configmap.yaml
- packages/rancher-windows-exporter/charts/templates/daemonset.yaml
- packages/rancher-windows-exporter/charts/templates/rbac.yaml
- packages/rancher-windows-exporter/charts/templates/service.yaml
- packages/rancher-windows-exporter/charts/templates/servicemonitor.yaml
- packages/rancher-windows-exporter/charts/templates/windows-relabel-rule.yaml
- packages/rancher-windows-exporter/charts/values.yaml
- packages/rancher-windows-exporter/package.yaml
Forward ports a newer version of exporter-node-windows from Monitoring V1.
The charts are content-wise the same but structured very differently, so no base copy commit was added.
Blocked on creation of image:
Related Issue: https://github.com/rancher/rancher/issues/28327, https://github.com/rancher/rancher/issues/31497
> Add rancher-windows-exporter

- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/README.md.patch
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Add a new value to the rancher-logging chart to enable setting the
seLinuxOptions securityContext attribute for Logging resources and the
rke-aggregator DaemonSet. This is applied to any resource that needs to
read from /var/log/containers or /var/lib/docker/containers.
Without this patch, components in the rancher-logging chart mount and
attempt to read and sometimes write files on several hostPaths, and when
SELinux is enabled on the host, will fail because the containers are
unauthorized to do so. The added seLinuxOptions attribute in this patch
causes the fluentbit and rke-aggregator DaemonSets to run with the
SELinux context type `rke_logreader_t`, which is provided by the
rke2-linux package and enables the container to read files with the
label `container_log_t`, which includes …
> [2.5.8] Add global seLinux toggle to rancher-logging

- packages/rancher-cis-benchmark/charts/Chart.yaml
- packages/rancher-cis-benchmark/charts/values.yaml
- packages/rancher-cis-benchmark/package.yaml
- packages/rancher-gatekeeper/generated-changes/patch/values.yaml.patch
- packages/rancher-gatekeeper/package.yaml
- packages/rancher-gatekeeper/templates/crd-template/values.yaml
- packages/rancher-monitoring/generated-changes/patch/values.yaml.patch
- packages/rancher-monitoring/package.yaml
- packages/rancher-monitoring/templates/crd-template/values.yaml
Bumps images to the latest available today.
Modifies rancher-monitoring, rancher-gatekeeper, and rancher-cis-benchmark.
Related Issue: https://github.com/rancher/rancher/issues/31729
> Bump kubectl and agent versions across feature charts

- configuration.yaml
Allows https://github.com/rancher/charts/pull/1067 to run `make sync` to keep dev-v2.6 in sync with both dev-v2.5 and dev-v2.6
> Keep dev-v2.6 in sync with dev-v2.5-source

- .github/workflows/pull-request.yaml
- .github/workflows/push.yaml
- configuration.yaml
Temporarily modifies our PR workflows to validate that we aren't corrupting changes in the dev-v2.6 branch and modifies our push workflow to also trigger a make sync on dev-v2.6, which will absorb changes from dev-v2.5-source pending https://github.com/rancher/charts/pull/1068.
> Add workflows to keep dev-v2.6 in sync

- charts/haproxy/v1.1.4/questions.yml
- charts/haproxy/v1.4.2/questions.yml
To ensure these charts are not used in newer releases of Rancher in favour of the updated “Partner Charts”
> Add rancher version constraint to HAproxy chart

- packages/rancher-logging/generated-changes/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
Fluentd process can silently die, leaving the container running.  Have added a liveness probe to check that the Fluentd port is open and listening
Fixes #1043
> Add liveness probe to fluentd

- .github/workflows/push.yaml
Fixes issues that require restarts due to unclean Git as a result of adding the 2.6 steps by just cleaning up Git entirely before running the 2.6 synchronization.
> Fix Github Push workflow

- packages/rancher-istio-1.8/charts/Chart.yaml
- packages/rancher-istio-1.8/charts/values.yaml
- packages/rancher-istio-1.8/package.yaml
- packages/rancher-istio-1.9/charts/Chart.yaml
- packages/rancher-istio-1.9/charts/values.yaml
- packages/rancher-istio-1.9/package.yaml
- packages/rancher-kiali-server/generated-changes/patch/Chart.yaml.patch
- packages/rancher-kiali-server/generated-changes/patch/values.yaml.patch
- packages/rancher-kiali-server/package.yaml
- packages/rancher-kiali-server/templates/crd-template/Chart.yaml
**Problem**
Warning is showing up in logs with ```Warning: CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+```. This was resolved upstream here: https://github.com/kiali/helm-charts/pull/35
**Solution**
Update Kiali to the most recent v1.32.0 version that has a fix for the crd api. The fix was implemented starting in version 1.29.1, but am going with the most recent because it contains the fix along with newer features. Kiali version >=v1.26 is compatible with Istio 1.8 and 1.9 (https://kiali.io/documentation/latest/installation-guide/#_version_compatibility) 
**Issues**
https://github.com/rancher/rancher/issues/31979
https://github.com/rancher/rancher/issues/31514
> Kiali v1.32.0

- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/dashboards/rancher/default-dashboard.yaml
- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/dashboards/rancher/etcd-dashboards.yaml
- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/dashboards/rancher/k8s-dashboards.yaml
- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/dashboards/rancher/linux-dashboards.yaml
- packages/rancher-monitoring/generated-changes/overlay/templates/rancher-monitoring/dashboards/rancher/windows-dashboards.yaml
- packages/rancher-monitoring/package.yaml
Currently, we prefix dashboards based on logic similar to `{{ .Chart.Name }}-<dashboard>`.
However, when Grafana has a default dashboard with the same name as Rancher, the name becomes the same, which results in a conflict, re: https://github.com/rancher/rancher/issues/32024#issuecomment-818312832
While one solution for this would be to just ensure there is no overlap between the dashboard ConfigMap names chosen by Rancher and Grafana, an easier fix seems to be just to change the naming prefix of dashboards that are deployed by default by Rancher instead.
Therefore, we can have a `rancher-monitoring-etcd` deployed by default with Grafana as well as a `rancher-default-dashboards-etcd` to keep the name etcd but avoid conflict.
Related Issue: https://github.com/rancher/rancher/issues/32024
> Use a different prefix for Rancher dashboards than the Chart name

- packages/rancher-backup-crd/generated-changes/patch/Chart.yaml.patch
- packages/rancher-backup-crd/package.yaml
Relevant issue: https://github.com/rancher/rancher/issues/32152
Appears that we accidentally missed the CRD chart here: https://github.com/rancher/charts/pull/1082
> Match backup crd version to primary chart with 1.0.4-rc3

- packages/rancher-alerting-drivers/charts/Chart.yaml
- packages/rancher-alerting-drivers/package.yaml
- packages/rancher-prom2teams/generated-changes/overlay/templates/psp.yaml
- packages/rancher-prom2teams/generated-changes/overlay/templates/role.yaml
- packages/rancher-prom2teams/generated-changes/overlay/templates/rolebinding.yaml
- packages/rancher-prom2teams/package.yaml
- packages/rancher-sachet/charts/templates/deployment.yaml
- packages/rancher-sachet/charts/templates/psp.yaml
- packages/rancher-sachet/charts/templates/role.yaml
- packages/rancher-sachet/charts/templates/rolebinding.yaml
- packages/rancher-sachet/charts/values.yaml
- packages/rancher-sachet/package.yaml
This PR contains the following changes:
- add supports for reloading the configMap in rancher-sachet
- add supports for pod security policy in rancher-sachet and rancher-prom2teams
related PR: https://github.com/rancher/charts/pull/1085
related issue: https://github.com/rancher/rancher/issues/29951
> [rancher-alerting-drivers] configmap-reloader and PSP

- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/configmap.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/daemonset.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
PROBLEM:
we were not getting any of the rke2 systemd logs
SOLUTION:
fluentbit's journald plugin needs the machine id to work correctly
TESTING:
installed logging on an rke2 cluster and was able to get this log message
```
{"_MACHINE_ID":"59e806f5bba74a5d8addb46a60a7ce78","PRIORITY":"6","SYSLOG_FACILITY":"3","_UID":"0","_GID":"0","_SELINUX_CONTEXT":"unconfined\n","_SYSTEMD_SLICE":"system.slice","_TRANSPORT":"stdout","_CAP_EFFECTIVE":"3fffffffff","_HOSTNAME":"jpayne-rke2","SYSLOG_IDENTIFIER":"rke2","_COMM":"rke2","_EXE":"/usr/local/bin/rke2","_SYSTEMD_CGROUP":"/system.slice/rke2-server.service","_SYSTEMD_UNIT":"rke2-server.service","_CMDLINE":"/usr/local/bin/rke2 server","_BOOT_ID":"caa7ced9023945a482a7e0bb726c1dbf","_STREAM_ID":"837d3787b0f548fc9cc3f633c08b988f","_PID":"15517","_SYSTEMD_INV …
```
> fixed journald aggregation for rke2

- packages/rancher-alerting-drivers/package.yaml
- packages/rancher-prom2teams/generated-changes/patch/templates/configmap.yaml.patch
- packages/rancher-prom2teams/package.yaml
- packages/rancher-sachet/charts/templates/configmap-pre-install.yaml
- packages/rancher-sachet/package.yaml
Issue: https://github.com/rancher/rancher/issues/32249
Problem:
If we enable a new driver when doing a helm upgrade, the new configMap will not be created because configmaps are created only when a `helm install` happens. 
Fix:
Create the configmaps if it is missing when a `helm upgrade` happens.
> fix the issue where the configmap is missing when upgrading rancher-alerting-drives to enable a new driver

- packages/rancher-monitoring/package.yaml
- packages/rancher-monitoring/templates/crd-template/README.md
- packages/rancher-monitoring/templates/crd-template/templates/jobs.yaml
- packages/rancher-monitoring/templates/crd-template/values.yaml
The first commit reverts a change introduced in a previous commit that deletes CRDs before re-installing them. This is not an option in a production environment since it would wipe out all of the CRs in the cluster, which would effectively remove any customization that a user added between Monitoring chart upgrades.
The second commit modifies the CRD chart to use rancher/agent instead of rancher/kubectl (since we need to perform some light scripting and `sh` is not offered in rancher/kubectl).
Once the image was modified, I changed the remove-finalizer container to avoid doing an entire kubectl apply in favor of just removing the finalizers (the original intention of the container) and added a new initContainer on install that would destroy the preserveUnknownField on an upgrade due to an …
> Fix CRD chart regression and fix CRDs for upgrades

- .github/workflows/push-2.6.yaml
Blocked on https://github.com/rancher/charts/pull/1136.
Related Issue: https://github.com/rancher/rancher/issues/32146
> Add stage-release workflow for 2.6

- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
- rancher/rancher#28721
- rancher/dashboard#2684
- rancher/rancher#32264
> Add option to disable Windows logging for Windows clusters

- packages/rancher-istio-1.8/charts/values.yaml
- packages/rancher-istio-1.8/package.yaml
- packages/rancher-istio-1.9/charts/configs/istio-base.yaml
- packages/rancher-istio-1.9/charts/values.yaml
- packages/rancher-istio-1.9/package.yaml
**Problem**
istiocoredns is not longer supported in the IstioOperator file
istio-installer is not catching errors for istioctl install and upgrade commands so helm is reporting a successful install even when not true. 
**Solution**
Remove istiocoredns from the IstioOperator base-config map. Updated the 1.8 values.yaml to indicate that it will be unsupported in 1.9. 
Use new istio-intaller image that catches errors for istioctl commands 
**Issue**
https://github.com/rancher/rancher/issues/32252
Dependent: https://github.com/rancher/istio-installer/pull/23
> Removed istiocoredns from 1.9

- packages/rancher-alerting-drivers/package.yaml
- packages/rancher-sachet/charts/templates/configmap-pre-install.yaml
- packages/rancher-sachet/package.yaml
issue https://github.com/rancher/rancher/issues/32296
Note:
Because the change is only in `rancher-sachet`, so bump the versions of `rancher-sachet` and `rancher-alerting-drivers`, NOT `rancher-prom2teams`.
> changes in rancher-sachet: add the link to the upstream example

- packages/rancher-monitoring/generated-changes/overlay/files/rancher/k8s/rancher-etcd-nodes.json
- packages/rancher-monitoring/generated-changes/overlay/files/rancher/k8s/rancher-etcd.json
- packages/rancher-monitoring/generated-changes/overlay/files/rancher/pods/rancher-pod-containers.json
- packages/rancher-monitoring/generated-changes/overlay/files/rancher/pods/rancher-pod.json
- packages/rancher-monitoring/generated-changes/overlay/files/rancher/workloads/rancher-workload-pods.json
- packages/rancher-monitoring/generated-changes/overlay/files/rancher/workloads/rancher-workload.json
- packages/rancher-monitoring/package.yaml
Quick fix to change units to since all of the PromQL metrics are based on bytes, not kilobytes.
For future, we can use https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/categories.ts to identify the key value pairs that are tied to certain units showing up on the Grafana dashboard.
Related Issue: https://github.com/rancher/rancher/issues/32357
> Fix units to bytes, not kb

- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/templates/_helpers.tpl
- packages/rancher-windows-exporter/charts/templates/daemonset.yaml
- packages/rancher-windows-exporter/package.yaml
- packages/rancher-wins-upgrader/package.yaml
Wins PR: https://github.com/rancher/wins/pull/36
Related Issue: https://github.com/rancher/rancher/issues/32194
> Allow rancher-wins-upgrader and rancher-windows-exporter to default to c:/ if rkeWindowsPathPrefix is ""

- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/templates/_helpers.tpl
- packages/rancher-windows-exporter/package.yaml
Reverts change that was accidentally introduced in https://github.com/rancher/charts/pull/1172 to modify the helper template name:
https://github.com/rancher/charts/pull/1172/files#diff-2b0747e6ecba415652b5430ad7ae97c9d55f752c6de682d8cd2f23443e56f1d4R66
Related Issue: https://github.com/rancher/rancher/issues/32194
> Revert change to helper function name

- packages/rancher-cis-benchmark/charts/values.yaml
- packages/rancher-cis-benchmark/package.yaml
Updating with non-rc tags for rancher-cis-benchmark
> Updating CIS chart image tags to use non-rc tags to release 1.0.400

- packages/rancher-monitoring/generated-changes/patch/values.yaml.patch
- packages/rancher-monitoring/package.yaml
- packages/rancher-windows-exporter/charts/scripts/run.ps1
- packages/rancher-windows-exporter/charts/templates/configmap.yaml
- packages/rancher-windows-exporter/charts/templates/daemonset.yaml
- packages/rancher-windows-exporter/charts/templates/rbac.yaml
- packages/rancher-windows-exporter/charts/templates/service.yaml
- packages/rancher-windows-exporter/package.yaml
- packages/rancher-wins-upgrader/package.yaml
The reason why this change is necessary is that wins performs a checksum on the exact same path that must exist in the container and must exist on the host. Therefore, even though there is no need for the container to have knowledge of the CATTLE_PREFIX_PATH, it must for wins to be able to checksum correctly.
Related Issue: https://github.com/rancher/rancher/issues/32194, https://github.com/rancher/rancher/issues/32530
Wins PR: https://github.com/rancher/wins/pull/39
> Put binary in prefixPath within container

- packages/rancher-logging/generated-changes/overlay/app-readme.md
- packages/rancher-logging/generated-changes/overlay/templates/loggings/aks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/eks/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/gke/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-openrc.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/k3s/logging-k3s-systemd.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/configmap.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/configmap.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/daemonset.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/rke2/logging-rke2-containers.yaml
- packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml
- packages/rancher-logging/generated-changes/overlay/templates/userroles.yaml
- packages/rancher-logging/generated-changes/overlay/templates/validate-install.yaml
- packages/rancher-logging/generated-changes/patch/Chart.yaml.patch
- packages/rancher-logging/generated-changes/patch/README.md.patch
- packages/rancher-logging/generated-changes/patch/templates/_helpers.tpl.patch
- packages/rancher-logging/generated-changes/patch/templates/deployment.yaml.patch
- packages/rancher-logging/generated-changes/patch/values.yaml.patch
- packages/rancher-logging/package.yaml
- packages/rancher-logging/templates/crd-template/Chart.yaml
- packages/rancher-logging/templates/crd-template/README.md
This PR is split into two commits: a copy commit, similar to PRs in [rancher/system-charts](https://github.com/rancher/system-charts), and a commit with the desired changes.
- Add the `rancher-logging` package from `dev-v2.5-source` with no changes
- Add RKE Windows PathPrefix and standardize Windows paths within the logging chart (continuation of #1169)
- Add buffer configuration for `fluent-bit` for logging (continuation of #1121)
- Add `fluentd` options from frequent requests (originally from @dbason; continuation of #1112)
- Tidy the Logging CRs in the chart for style consistency and general cleanup (it also addresses: https://github.com/rancher/charts/pull/1182#commitcomment-50398194)
1. All continuations of PRs were already approved and reviewed
1. Given the slated timing for 2.6 …
> Add rancher-logging to 2.6 among multiple changes

- index.yaml
Problem:
When Helm generates the index.yaml, it skips the existing ones(determined by version). As a result, all those existing charts to which we added the annotation are not updated in the index.yaml
Fix:
wipe the index.yaml and rerun the `make charts` command
> fix the index.yaml file

- index.yaml
Followup to https://github.com/rancher/charts/pull/1541. The index.yaml also needs to be pulled in.
---
This is the equivalent of running the following script:
```
git fetch upstream
git checkout upstream/release-v2.6 -- index.yaml
git add index.yaml
git commit -m "Inherit index.yaml from release-v2.6"
make charts
git add index.yaml
git commit --amend --no-edit
```
> Inherit index.yaml from release-v2.6

- .gitignore
- README.md
- scripts/version
What does the PR do:
- bump the charts-build-script to v0.2.4
- run make template
> Update the charts-build-script to v0.2.4 in dev-v2.6

- configuration.yaml
- release.yaml
Currently, our release.yaml validates against the contents of dev-v2.6, not release-v2.6.
It should be validating against release instead.
> Change validate.branch to release-v2.6

- release.yaml
The deletions are charts that have already been released and are listed in the release.yaml in the release-v2.6 branch.
> Clean up old releases in release.yaml

- .github/workflows/pull-request.yaml
CI should be running on OOB release branches like https://github.com/rancher/charts/pull/2046.
> Run CI workflows on all dev and release branches
